def GetData():
    arr = [('gr', '60 Kg', 'Liguo CAO', 'Galym KABDUNASSAROV', ('7', '3'), 'Liguo CAO', 'by VPO1', 'Apr 2024'),
    ('gr', '60 Kg', 'Liguo CAO', 'Mark Ervin OLIVEROS', ('8', '0'), 'Liguo CAO', 'by VSU', 'Apr 2024'),
    ('gr', '60 Kg', 'Kaito INABA', 'Liguo CAO', ('11', '1'), 'Kaito INABA', 'by VSU1', 'Apr 2024'),
    ('gr', '60 Kg', 'Liguo CAO', 'Baljinnyam TSEVEENRAVDAN', ('9', '1'), 'Liguo CAO', 'by VSU1', 'Apr 2024'),
    ('gr', '60 Kg', 'Pridon ABULADZE', 'Liguo CAO', ('4', '2'), 'Pridon ABULADZE', 'by VPO1', 'Jan 2024'),
    ('gr', '60 Kg', 'Liguo CAO', 'Hayden Daniel TUMA', ('9', '1'), 'Liguo CAO', 'by VSU1', 'Jan 2024'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Liguo CAO', ('3', '1'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Oct 2023'),
    ('gr', '60 Kg', 'Liguo CAO', 'Pros CHRAY', ('8', '0'), 'Liguo CAO', 'by VSU', 'Oct 2023'),
    ('gr', '60 Kg', 'Liguo CAO', 'Gevorg GHARIBYAN', ('5', '3'), 'Liguo CAO', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Liguo CAO', 'Victor CIOBANU', ('9', '7'), 'Liguo CAO', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Kenichiro FUMITA', 'Liguo CAO', ('3', '1'), 'Kenichiro FUMITA', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Liguo CAO', 'Leo Alexandre Sylvain TUDEZCA', ('6', '4'), 'Liguo CAO', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Liguo CAO', 'Melkamu FETENE', ('5', '1'), 'Liguo CAO', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Seunghak KIM', 'Liguo CAO', ('10', '7'), 'Seunghak KIM', 'by VPO1', 'Jul 2023'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Liguo CAO', ('10', '1'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU1', 'Jun 2023'),
    ('gr', '60 Kg', 'Liguo CAO', 'Yernur FIDAKHMETOV', ('4', '2'), 'Liguo CAO', 'by VPO1', 'Apr 2023'),
    ('gr', '60 Kg', 'Liguo CAO', 'Aslamjon AZIZOV', ('3', '1'), 'Liguo CAO', 'by VPO1', 'Apr 2023'),
    ('gr', '60 Kg', 'Hanjae CHUNG', 'Liguo CAO', ('3', '1'), 'Hanjae CHUNG', 'by VPO1', 'Apr 2023'),
    ('gr', '60 Kg', 'Razvan ARNAUT', 'Liguo CAO', ('8', '0'), 'Razvan ARNAUT', 'by VSU', 'Feb 2023'),
    ('gr', '60 Kg', 'Kerem KAMAL', 'Liguo CAO', ('5', '2'), 'Kerem KAMAL', 'by VPO1', 'Feb 2023'),
    ('gr', '60 Kg', 'Liguo CAO', 'Pridon ABULADZE', ('5', '2'), 'Liguo CAO', 'by VPO1', 'Feb 2023'),
    ('gr', '60 Kg', 'Kaito INABA', 'Liguo CAO', ('5', '1'), 'Kaito INABA', 'by VPO1', 'Feb 2023'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Liguo CAO', ('8', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU', 'Feb 2023'),
    ('gr', '60 Kg', 'Liguo CAO', 'Gyanender GYANENDER', ('9', '0'), 'Liguo CAO', 'by VSU', 'Feb 2023'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Liguo CAO', ('7', '1'), 'Aidos SULTANGALI', 'by VPO1', 'Sep 2022'),
    ('gr', '60 Kg', 'Liguo CAO', 'Gyanender GYANENDER', ('11', '0'), 'Liguo CAO', 'by VSU', 'Sep 2022'),
    ('gr', '60 Kg', 'Liguo CAO', 'Abdelkarim FERGAT', ('9', '0'), 'Liguo CAO', 'by VSU', 'Sep 2022'),
    ('gr', '60 Kg', 'Artur Muchegovitch PETROSIAN', 'Liguo CAO', ('3', '1'), 'Artur Muchegovitch PETROSIAN', 'by VPO1', 'Oct 2019'),
    ('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Liguo CAO', ('9', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Oct 2019'),
    ('gr', '60 Kg', 'Liguo CAO', 'Rysgal KUVATGELDIYEV', ('12', '9'), 'Liguo CAO', 'by VPO1', 'Oct 2019'),
    ('gr', '60 Kg', 'Liguo CAO', 'Sachin RANA', ('5', '2'), 'Liguo CAO', 'by VPO1', 'Oct 2019'),
    ('gr', '60 Kg', 'Shota OGAWA', 'Liguo CAO', ('11', '2'), 'Shota OGAWA', 'by VSU1', 'Sep 2019'),
    ('gr', '60 Kg', 'Liguo CAO', 'Vitalii KABALOEV', ('5', '4'), 'Liguo CAO', 'by VFA', 'Sep 2019'),
    ('gr', '60 Kg', 'Nugzari TSURTSUMIA', 'Liguo CAO', ('9', '0'), 'Nugzari TSURTSUMIA', 'by VSU', 'Sep 2019'),
    ('gr', '60 Kg', 'Di HU', 'Liguo CAO', ('2', '1'), 'Di HU', 'by VPO1', 'Feb 2019'),
    ('gr', '60 Kg', 'Shirzad Ali BEHESHTITALA', 'Liguo CAO', ('8', '1'), 'Shirzad Ali BEHESHTITALA', 'by VCA', 'Feb 2019'),
    ('gr', '60 Kg', 'Liguo CAO', 'Bence KOVACS', ('3', '3'), 'Liguo CAO', 'by VPO1', 'Feb 2019'),
    ('gr', '60 Kg', 'Firuz TUKHTAEV', 'Liguo CAO', ('9', '0'), 'Firuz TUKHTAEV', 'by VSU', 'Feb 2019'),
    ('gr', '60 Kg', 'Liguo CAO', 'Jacopo SANDRON', ('5', '4'), 'Liguo CAO', 'by VPO1', 'Feb 2019'),
    ('gr', '60 Kg', 'Nugzari TSURTSUMIA', 'Liguo CAO', ('11', '0'), 'Nugzari TSURTSUMIA', 'by VSU', 'Oct 2018'),
    ('gr', '60 Kg', 'Liguo CAO', 'Shota TANOKURA', ('5', '5'), 'Liguo CAO', 'by VPO1', 'Oct 2018'),
    ('gr', '60 Kg', 'Liguo CAO', 'Jozsef ANDRASI', ('10', '0'), 'Liguo CAO', 'by VSU', 'Oct 2018'),
    ('gr', '60 Kg', 'Eldaniz AZIZLI', 'Liguo CAO', ('9', '0'), 'Eldaniz AZIZLI', 'by VSU', 'Oct 2018'),
    ('gr', '60 Kg', 'Liguo CAO', 'Vijay VIJAY', ('9', '1'), 'Liguo CAO', 'by VSU1', 'Oct 2018'),
    ('gr', '60 Kg', 'Jozsef ANDRASI', 'Liguo CAO', ('3', '0'), 'Jozsef ANDRASI', 'by VPO', 'Jun 2018'),
    ('gr', '60 Kg', 'Khorlan ZHAKANSHA', 'Liguo CAO', ('8', '0'), 'Khorlan ZHAKANSHA', 'by VSU', 'Jun 2018'),
    ('gr', '60 Kg', 'Liguo CAO', 'Amangali BEKBOLATOV', ('13', '8'), 'Liguo CAO', 'by VPO1', 'Jun 2018'),
    ('gr', '60 Kg', 'Khorlan ZHAKANSHA', 'Liguo CAO', ('7', '4'), 'Khorlan ZHAKANSHA', 'by VPO1', 'Feb 2018'),
    ('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Liguo CAO', ('8', '2'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Feb 2018'),
    ('gr', '60 Kg', 'Liguo CAO', 'Hayder Talib Mallak AL SAEDI', ('0', '0'), 'Liguo CAO', 'by DSQ', 'Feb 2018'),
    ('gr', '60 Kg', 'Turabek TIRKASHEV', 'Liguo CAO', ('9', '1'), 'Turabek TIRKASHEV', 'by VSU1', 'Aug 2017'),
    ('gr', '60 Kg', 'Liguo CAO', 'Sanshiro TAKAHASHI', ('8', '5'), 'Liguo CAO', 'by VPO1', 'Aug 2017'),
    ('gr', '60 Kg', 'Liguo CAO', 'Ilkhom BAKHROMOV', ('9', '0'), 'Liguo CAO', 'by VSU', 'Jun 2017'),
    ('gr', '60 Kg', 'Mohammad Javad Saadat REZAEI', 'Liguo CAO', ('9', '0'), 'Mohammad Javad Saadat REZAEI', 'by VSU', 'Jun 2017'),
    ('gr', '60 Kg', 'Liguo CAO', 'Hiromu KATAGIRI', ('5', '4'), 'Liguo CAO', 'by VPO1', 'Jun 2017'),
    ('gr', '60 Kg', 'Chan KIM', 'Islomjon BAKHRAMOV', ('3', '1'), 'Chan KIM', 'by VPO1', 'Apr 2024'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Dastan KADYROV', ('8', '5'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Apr 2024'),
    ('gr', '60 Kg', 'Hanjae CHUNG', 'Islomjon BAKHRAMOV', ('5', '4'), 'Hanjae CHUNG', 'by VPO1', 'Oct 2023'),
    ('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Islomjon BAKHRAMOV', ('11', '0'), 'Zholaman SHARSHENBEKOV', 'by VFA', 'Oct 2023'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Liguo CAO', ('3', '1'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Oct 2023'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Tien Hai BUI', ('8', '0'), 'Islomjon BAKHRAMOV', 'by VSU', 'Oct 2023'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Mehdi Seifollah MOHSEN NEJAD', ('3', '3'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Pridon ABULADZE', ('7', '4'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Islomjon BAKHRAMOV', ('10', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Sep 2023'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Hleb MAKARANKA', ('9', '0'), 'Islomjon BAKHRAMOV', 'by VSU', 'Sep 2023'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('10', '1'), 'Islomjon BAKHRAMOV', 'by VSU1', 'Sep 2023'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Nursultan BAZARBAYEV', ('6', '0'), 'Islomjon BAKHRAMOV', 'by VPO', 'Jun 2023'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Mehdi Seifollah MOHSEN NEJAD', ('3', '3'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Jun 2023'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Aftandil TAALAIBEK UULU', ('10', '2'), 'Islomjon BAKHRAMOV', 'by VSU1', 'Jun 2023'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Erbatu TUO', ('5', '3'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Jun 2023'),
    ('gr', '60 Kg', 'Neeraj NEERAJ', 'Islomjon BAKHRAMOV', ('7', '4'), 'Neeraj NEERAJ', 'by VPO1', 'Apr 2022'),
    ('gr', '60 Kg', 'Tynar SHARSHENBEKOV', 'Islomjon BAKHRAMOV', ('13', '7'), 'Tynar SHARSHENBEKOV', 'by VFA', 'Apr 2022'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Jinseub SONG', ('9', '1'), 'Islomjon BAKHRAMOV', 'by VSU1', 'Apr 2022'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Victor CIOBANU', ('9', '0'), 'Islomjon BAKHRAMOV', 'by VSU', 'Feb 2022'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Dastan KADYROV', ('9', '1'), 'Islomjon BAKHRAMOV', 'by VSU1', 'Feb 2022'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Rahman BILICI', ('9', '6'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Feb 2022'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Taleh MAMMADOV', ('8', '2'), 'Islomjon BAKHRAMOV', 'by VFA', 'Feb 2022'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Ayata SUZUKI', ('5', '3'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Jun 2021'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Krisztian KECSKEMETI', ('7', '0'), 'Islomjon BAKHRAMOV', 'by VFA', 'Jun 2021'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Mairbek SALIMOV', ('6', '0'), 'Islomjon BAKHRAMOV', 'by VFA', 'Jun 2021'),
    ('gr', '60 Kg', 'Ayata SUZUKI', 'Islomjon BAKHRAMOV', ('9', '0'), 'Ayata SUZUKI', 'by VSU', 'Apr 2021'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Ahmet UYAR', ('9', '0'), 'Islomjon BAKHRAMOV', 'by VSU', 'Jan 2021'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Firuz TUKHTAEV', ('3', '2'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Jan 2021'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Micha TRACZ', ('8', '0'), 'Islomjon BAKHRAMOV', 'by VSU', 'Jan 2021'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Alexander BICA', ('8', '0'), 'Islomjon BAKHRAMOV', 'by VSU', 'Jan 2021'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Gyanender GYANENDER', ('6', '0'), 'Islomjon BAKHRAMOV', 'by VPO', 'Feb 2020'),
    ('gr', '60 Kg', 'Kenichiro FUMITA', 'Islomjon BAKHRAMOV', ('9', '0'), 'Kenichiro FUMITA', 'by VSU', 'Feb 2020'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Firuz MIRZORAJABOV', ('9', '0'), 'Islomjon BAKHRAMOV', 'by VCA', 'Feb 2020'),
    ('gr', '60 Kg', 'Sailike WALIHAN', 'Islomjon BAKHRAMOV', ('4', '3'), 'Sailike WALIHAN', 'by VPO1', 'Jan 2020'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Sachin RANA', ('9', '0'), 'Islomjon BAKHRAMOV', 'by VSU', 'Jan 2020'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Firuz TUKHTAEV', ('8', '7'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Jan 2020'),
    ('gr', '60 Kg', 'Slavik GALSTYAN', 'Islomjon BAKHRAMOV', ('3', '3'), 'Slavik GALSTYAN', 'by VPO1', 'Sep 2019'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Oleksandr HRUSHYN', ('5', '2'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Sep 2019'),
    ('gr', '60 Kg', 'Shinobu OTA', 'Islomjon BAKHRAMOV', ('11', '1'), 'Shinobu OTA', 'by VSU1', 'Jul 2019'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Sailike WALIHAN', ('3', '3'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Jul 2019'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Erbatu TUO', ('10', '7'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Jul 2019'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Sagar SAGAR', ('5', '2'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Jul 2019'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Se Ung RI', ('12', '4'), 'Islomjon BAKHRAMOV', 'by VSU1', 'Apr 2019'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Gyanender GYANENDER', ('9', '0'), 'Islomjon BAKHRAMOV', 'by VSU', 'Apr 2019'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Jui Chi HUANG', ('9', '0'), 'Islomjon BAKHRAMOV', 'by VSU', 'Apr 2019'),
    ('gr', '60 Kg', 'Ivan LIZATOVIC', 'Islomjon BAKHRAMOV', ('7', '7'), 'Ivan LIZATOVIC', 'by VPO1', 'Feb 2019'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Xavier Tramain JOHNSON', ('10', '2'), 'Islomjon BAKHRAMOV', 'by VSU1', 'Feb 2019'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Firuz TUKHTAEV', ('5', '0'), 'Islomjon BAKHRAMOV', 'by VPO', 'Feb 2019'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Travis Michael RICE', ('9', '0'), 'Islomjon BAKHRAMOV', 'by VSU', 'Feb 2019'),
    ('gr', '60 Kg', 'Kerem KAMAL', 'Islomjon BAKHRAMOV', ('9', '1'), 'Kerem KAMAL', 'by VSU1', 'Nov 2018'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Dato CHKHARTISHVILI', ('9', '4'), 'Islomjon BAKHRAMOV', 'by VFA', 'Nov 2018'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Rustam TEIISHOV', ('11', '3'), 'Islomjon BAKHRAMOV', 'by VSU1', 'Nov 2018'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Islomjon BAKHRAMOV', ('8', '0'), 'Murad MAMMADOV', 'by VSU', 'Nov 2018'),
    ('gr', '60 Kg', 'Mehrdad Abdmohammad MARDANI', 'Islomjon BAKHRAMOV', ('8', '0'), 'Mehrdad Abdmohammad MARDANI', 'by VSU', 'Aug 2018'),
    ('gr', '60 Kg', 'Shinobu OTA', 'Islomjon BAKHRAMOV', ('6', '0'), 'Shinobu OTA', 'by VPO', 'Aug 2018'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Gyanender GYANENDER', ('5', '0'), 'Islomjon BAKHRAMOV', 'by VPO', 'Aug 2018'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Yu Hung LIN', ('10', '0'), 'Islomjon BAKHRAMOV', 'by VSU', 'Aug 2018'),
    ('gr', '60 Kg', 'Mehrdad Abdmohammad MARDANI', 'Islomjon BAKHRAMOV', ('3', '2'), 'Mehrdad Abdmohammad MARDANI', 'by VPO1', 'Jul 2018'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Firuz TUKHTAEV', ('1', '1'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Jul 2018'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Ramaz SURMANIDZE', ('6', '2'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Jul 2018'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Irakli SHAVADZE', ('7', '1'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Jul 2018'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Amiran SHAVADZE', ('15', '3'), 'Islomjon BAKHRAMOV', 'by VSU1', 'Jul 2018'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Yu Hung LIN', ('8', '0'), 'Islomjon BAKHRAMOV', 'by VSU', 'Feb 2018'),
    ('gr', '60 Kg', 'Se Ung RI', 'Islomjon BAKHRAMOV', ('8', '0'), 'Se Ung RI', 'by VSU', 'Feb 2018'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Seunghak KIM', ('10', '5'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Feb 2018'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Gyanender GYANENDER', ('8', '0'), 'Islomjon BAKHRAMOV', 'by VFA', 'Feb 2018'),
    ('gr', '60 Kg', 'Abdulmazhit BAKIZHONOV', 'Islomjon BAKHRAMOV', ('3', '2'), 'Abdulmazhit BAKIZHONOV', 'by VPO1', 'Jan 2017'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Nikita KOZHEVNIKOV', ('10', '10'), 'Islomjon BAKHRAMOV', 'by VFA', 'Jan 2017'),
    ('gr', '60 Kg', 'Mingiyan SEMENOV', 'Islomjon BAKHRAMOV', ('6', '0'), 'Mingiyan SEMENOV', 'by VPO', 'Jan 2017'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Slavik GALSTYAN', ('9', '1'), 'Islomjon BAKHRAMOV', 'by VFA', 'Aug 2015'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Meysam DALKHANI', ('10', '0'), 'Islomjon BAKHRAMOV', 'by VSU', 'Aug 2015'),
    ('gr', '60 Kg', 'Murad MOMMADOV', 'Islomjon BAKHRAMOV', ('8', '0'), 'Murad MOMMADOV', 'by VSU', 'Aug 2015'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Irakli SHAVADZE', ('9', '1'), 'Islomjon BAKHRAMOV', 'by VSU1', 'Aug 2015'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Yo NAMBA', ('9', '1'), 'Islomjon BAKHRAMOV', 'by VSU1', 'Aug 2015'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Mehdi Seifollah MOHSEN NEJAD', ('3', '3'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Mehdi Seifollah MOHSEN NEJAD', ('4', '3'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Christopher Josef KRAEMER', ('7', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VPO', 'Sep 2023'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Seunghak KIM', ('4', '2'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Ildar HAFIZOV', ('7', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VPO', 'Sep 2023'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Aftandil TAALAIBEK UULU', ('8', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU', 'Jun 2023'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Mehdi Seifollah MOHSEN NEJAD', ('3', '3'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Jun 2023'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Razvan ARNAUT', ('7', '2'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VPO1', 'Jun 2023'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Liguo CAO', ('10', '1'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU1', 'Jun 2023'),
    ('gr', '60 Kg', 'Yernur FIDAKHMETOV', 'Mehdi Seifollah MOHSEN NEJAD', ('4', '3'), 'Yernur FIDAKHMETOV', 'by VPO1', 'Apr 2023'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Nihat Zahid MAMMADLI', ('8', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU', 'Feb 2023'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Maito KAWANA', ('7', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VPO', 'Feb 2023'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Liguo CAO', ('8', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU', 'Feb 2023'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Kaito INABA', ('7', '3'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VPO1', 'Feb 2023'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Nihat Zahid MAMMADLI', ('5', '4'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VPO1', 'Nov 2022'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Nurmukhammet ABDULLAEV', ('5', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VPO', 'Nov 2022'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Kerem KAMAL', ('9', '7'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VPO1', 'Nov 2022'),
    ('gr', '60 Kg', 'Kerem KAMAL', 'Mehdi Seifollah MOHSEN NEJAD', ('4', '9'), 'Kerem KAMAL', 'by VFA', 'Sep 2022'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Hanjae CHUNG', ('8', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VFA', 'Sep 2022'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Gyanender GYANENDER', ('9', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU', 'Apr 2022'),
    ('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Mehdi Seifollah MOHSEN NEJAD', ('4', '0'), 'Zholaman SHARSHENBEKOV', 'by VIN', 'Apr 2022'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Ayata SUZUKI', ('5', '4'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VPO1', 'Apr 2022'),
    ('gr', '60 Kg', 'Anvar ALLAKHIAROV', 'Mehdi Seifollah MOHSEN NEJAD', ('7', '1'), 'Anvar ALLAKHIAROV', 'by VPO1', 'Nov 2021'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Pridon ABULADZE', ('5', '3'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VPO1', 'Nov 2021'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Mukhammadkodir YUSUPOV', ('8', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU', 'Nov 2021'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Dylan Steven GREGERSON', ('8', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU', 'Nov 2021'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Mehdi Seifollah MOHSEN NEJAD', ('8', '4'), 'Aidos SULTANGALI', 'by VPO1', 'Apr 2021'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Ayata SUZUKI', ('9', '1'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU1', 'Apr 2021'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Merdan ALLAYAROV', ('8', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU', 'Apr 2021'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Kuttubek ABDYKERIM UULU', ('8', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU', 'Apr 2021'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Aidos SULTANGALI', ('4', '3'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VPO1', 'Feb 2020'),
    ('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Mehdi Seifollah MOHSEN NEJAD', ('9', '2'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Feb 2020'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Karrar Abbas Mukasr ALBIDHAN', ('9', '1'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU1', 'Feb 2020'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Krisztian KECSKEMETI', ('9', '5'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VPO1', 'Oct 2019'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Martin Stoyanov VELEV', ('8', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU', 'Oct 2019'),
    ('gr', '60 Kg', 'Armen MELIKYAN', 'Mehdi Seifollah MOHSEN NEJAD', ('4', '0'), 'Armen MELIKYAN', 'by VPO', 'Oct 2019'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Ayata SUZUKI', ('10', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU', 'Oct 2019'),
    ('gr', '60 Kg', 'Dastan ZARLYKHANOV', 'Mehdi Seifollah MOHSEN NEJAD', ('8', '0'), 'Dastan ZARLYKHANOV', 'by VSU', 'Mar 2019'),
    ('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Mehdi Seifollah MOHSEN NEJAD', ('4', '0'), 'Zholaman SHARSHENBEKOV', 'by VPO', 'Mar 2019'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Tumentsogt BOLD', ('9', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU', 'Mar 2019'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Manish MANISH', ('5', '3'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VFA', 'Mar 2019'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Armen MELIKYAN', ('10', '1'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU1', 'Nov 2018'),
    ('gr', '60 Kg', 'Kenichiro FUMITA', 'Mehdi Seifollah MOHSEN NEJAD', ('7', '0'), 'Kenichiro FUMITA', 'by VPO', 'Nov 2018'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Razvan ARNAUT', ('8', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU', 'Nov 2018'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Helary MAEGISALU', ('8', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU', 'Nov 2018'),
    ('gr', '60 Kg', 'Nugzari TSURTSUMIA', 'Mehdi Seifollah MOHSEN NEJAD', ('7', '2'), 'Nugzari TSURTSUMIA', 'by VPO1', 'Aug 2016'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Randon Drew MIRANDA', ('8', '0'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU', 'Aug 2016'),
    ('gr', '60 Kg', 'Ilkhom BAKHROMOV', 'Mehdi Seifollah MOHSEN NEJAD', ('9', '1'), 'Ilkhom BAKHROMOV', 'by VSU1', 'Aug 2016'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Dicther Hans TORO CASTANEDA', ('9', '1'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VSU1', 'Feb 2024'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Alexis RODRIGUEZ HERNANDEZ', ('5', '1'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Randon Drew MIRANDA', ('8', '7'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Yerony Arturo LIRIA CARRERAS', ('6', '1'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Cristobal Alonso TORRES NUNEZ', ('8', '0'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VSU', 'Feb 2024'),
    ('gr', '60 Kg', 'Ihor KUROCHKIN', 'Raiber Jose RODRIGUEZ OROZCO', ('7', '2'), 'Ihor KUROCHKIN', 'by VPO1', 'Jan 2024'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Gyanender GYANENDER', ('8', '6'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VPO1', 'Jan 2024'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Cristobal Alonso TORRES NUNEZ', ('7', '1'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VPO1', 'Nov 2023'),
    ('gr', '60 Kg', 'Kevin Yuran DE ARMAS RODRIGUEZ', 'Raiber Jose RODRIGUEZ OROZCO', ('7', '1'), 'Kevin Yuran DE ARMAS RODRIGUEZ', 'by VPO1', 'Nov 2023'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Dicther Hans TORO CASTANEDA', ('7', '3'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VPO1', 'Nov 2023'),
    ('gr', '60 Kg', 'Aslamjon AZIZOV', 'Raiber Jose RODRIGUEZ OROZCO', ('3', '3'), 'Aslamjon AZIZOV', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Alexis RODRIGUEZ HERNANDEZ', ('7', '2'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VPO1', 'May 2023'),
    ('gr', '60 Kg', 'Dalton James ROBERTS', 'Raiber Jose RODRIGUEZ OROZCO', ('9', '0'), 'Dalton James ROBERTS', 'by VSU', 'May 2023'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Samuel MESROPIAN', ('8', '0'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VSU', 'May 2023'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Pedro Maximiliano GUTIERREZ URRUTIA', ('6', '0'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VPO', 'Oct 2022'),
    ('gr', '60 Kg', 'Jeremy Renzo PERALTA GONZALEZ', 'Raiber Jose RODRIGUEZ OROZCO', ('6', '6'), 'Jeremy Renzo PERALTA GONZALEZ', 'by VFA', 'Oct 2022'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Joao Marco BENAVIDES ROCHABRUN', ('10', '5'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VPO1', 'Oct 2022'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Erivan CONSTANTINO ROCHA', ('8', '0'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VSU', 'Oct 2022'),
    ('gr', '60 Kg', 'Dicther Hans TORO CASTANEDA', 'Raiber Jose RODRIGUEZ OROZCO', ('6', '5'), 'Dicther Hans TORO CASTANEDA', 'by VPO1', 'Oct 2022'),
    ('gr', '60 Kg', 'Rovshan BAYRAMOV', 'Raiber Jose RODRIGUEZ OROZCO', ('8', '0'), 'Rovshan BAYRAMOV', 'by VSU', 'Aug 2016'),
    ('gr', '60 Kg', 'Andres Roberto MONTANO ARROYO', 'Raiber Jose RODRIGUEZ OROZCO', ('9', '0'), 'Andres Roberto MONTANO ARROYO', 'by VSU', 'Mar 2016'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Jose Luis MAGALLANES DURAND', ('10', '2'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VSU1', 'Mar 2016'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Alex Salomon PINEDA MARIN', ('9', '0'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VPO', 'Mar 2016'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Jancel Miguel PIMENTEL GONZALEZ', ('4', '1'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VPO1', 'Mar 2016'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Jose Luis MAGALLANES DURAND', ('8', '0'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VSU', 'Feb 2016'),
    ('gr', '60 Kg', 'Alejandro SANCHO', 'Raiber Jose RODRIGUEZ OROZCO', ('12', '4'), 'Alejandro SANCHO', 'by VSU1', 'Feb 2016'),
    ('gr', '60 Kg', 'Raiber Jose RODRIGUEZ OROZCO', 'Gorge Nickford GONZALES BATIS', ('12', '0'), 'Raiber Jose RODRIGUEZ OROZCO', 'by VSU', 'Feb 2016'),
    ('gr', '60 Kg', 'Hamid Mohammad SORYAN', 'Raiber Jose RODRIGUEZ OROZCO', ('8', '0'), 'Hamid Mohammad SORYAN', 'by VSU', 'Sep 2015'),
    ('gr', '60 Kg', 'Jansel Rafael RAMIREZ', 'Raiber Jose RODRIGUEZ OROZCO', ('10', '1'), 'Jansel Rafael RAMIREZ', 'by VSU1', 'Apr 2015'),
    ('gr', '60 Kg', 'Kevin DE ARMAS', 'Yerony Arturo LIRIA CARRERAS', ('10', '0'), 'Kevin DE ARMAS', 'by VSU', 'Feb 2024'),
    ('gr', '60 Kg', 'Kevin DE ARMAS', 'Ildar HAFIZOV', ('7', '3'), 'Kevin DE ARMAS', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Hector SANCHEZ ZAPATA', 'Kevin DE ARMAS', ('0', '0'), 'Hector SANCHEZ ZAPATA', 'by DSQ', 'Feb 2024'),
    ('gr', '60 Kg', 'Carlos Esteban GONZALEZ VAHOS', 'Kevin DE ARMAS', ('0', '0'), 'Carlos Esteban GONZALEZ VAHOS', 'by DSQ', 'Feb 2024'),
    ('gr', '60 Kg', 'Hayden Daniel TUMA', 'Kevin DE ARMAS', ('8', '3'), 'Hayden Daniel TUMA', 'by DSQ', 'Feb 2024'),
    ('gr', '60 Kg', 'Ildar HAFIZOV', 'Kevin DE ARMAS', ('7', '5'), 'Ildar HAFIZOV', 'by VPO1', 'Nov 2023'),
    ('gr', '60 Kg', 'Kevin DE ARMAS', 'Raiber Jose RODRIGUEZ OROZCO', ('7', '1'), 'Kevin DE ARMAS', 'by VPO1', 'Nov 2023'),
    ('gr', '60 Kg', 'Kevin DE ARMAS', 'Cristobal Alonso TORRES NUNEZ', ('8', '0'), 'Kevin DE ARMAS', 'by VSU', 'Nov 2023'),
    ('gr', '60 Kg', 'Nihat Zahid MAMMADLI', 'Kevin DE ARMAS', ('6', '2'), 'Nihat Zahid MAMMADLI', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Kevin DE ARMAS', 'Dicther Hans TORO CASTANEDA', ('0', '0'), 'Kevin DE ARMAS', 'by VIN', 'May 2023'),
    ('gr', '60 Kg', 'Kevin DE ARMAS', 'Emerson Isaias FELIPE ORDONEZ', ('8', '3'), 'Kevin DE ARMAS', 'by VPO1', 'May 2023'),
    ('gr', '60 Kg', 'Jeremy Renzo PERALTA GONZALEZ', 'Kevin DE ARMAS', ('2', '1'), 'Jeremy Renzo PERALTA GONZALEZ', 'by VFA', 'May 2023'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Kevin DE ARMAS', ('12', '2'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU1', 'Sep 2022'),
    ('gr', '60 Kg', 'Andrej GINC', 'Kevin DE ARMAS', ('4', '2'), 'Andrej GINC', 'by VFA', 'Feb 2018'),
    ('gr', '60 Kg', 'Javier DUMENIGO GONZALEZ', 'Kevin DE ARMAS', ('7', '5'), 'Javier DUMENIGO GONZALEZ', 'by VPO1', 'Feb 2018'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Ismail ETTALIBI', ('5', '1'), 'Abdelkarim FERGAT', 'by VPO1', 'Mar 2024'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Ibrahim BUNDUKA', ('9', '0'), 'Abdelkarim FERGAT', 'by VSU', 'Mar 2024'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Jonathan GBEDZE', ('8', '0'), 'Abdelkarim FERGAT', 'by VSU', 'Mar 2024'),
    ('gr', '60 Kg', 'Ismail ETTALIBI', 'Abdelkarim FERGAT', ('4', '2'), 'Ismail ETTALIBI', 'by VPO1', 'Mar 2024'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Romio Ricardo GOLIATH', ('4', '2'), 'Abdelkarim FERGAT', 'by VPO1', 'Mar 2024'),
    ('gr', '60 Kg', 'Moamen Ahmed Rabie MOHAMED', 'Abdelkarim FERGAT', ('9', '2'), 'Moamen Ahmed Rabie MOHAMED', 'by VPO1', 'Mar 2024'),
    ('gr', '60 Kg', 'Haodong TAN', 'Abdelkarim FERGAT', ('3', '1'), 'Haodong TAN', 'by VPO1', 'Feb 2023'),
    ('gr', '60 Kg', 'Yernar FIDAKHMETOV', 'Abdelkarim FERGAT', ('10', '0'), 'Yernar FIDAKHMETOV', 'by VSU', 'Feb 2023'),
    ('gr', '60 Kg', 'Liguo CAO', 'Abdelkarim FERGAT', ('9', '0'), 'Liguo CAO', 'by VSU', 'Sep 2022'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Salim HAMDI', ('10', '4'), 'Abdelkarim FERGAT', 'by VPO1', 'Jul 2022'),
    ('gr', '60 Kg', 'Ayhan KARAKUS', 'Abdelkarim FERGAT', ('9', '0'), 'Ayhan KARAKUS', 'by VSU', 'Jul 2022'),
    ('gr', '60 Kg', 'Arjun HALAKURKI', 'Abdelkarim FERGAT', ('9', '0'), 'Arjun HALAKURKI', 'by VSU', 'Jul 2022'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Moustafa Hussein Fathy ALAMELDIN', ('7', '3'), 'Abdelkarim FERGAT', 'by VPO1', 'May 2022'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Fouad FAJARI', ('7', '2'), 'Abdelkarim FERGAT', 'by VPO1', 'May 2022'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Kenneth KOECH', ('8', '0'), 'Abdelkarim FERGAT', 'by VSU', 'May 2022'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Hamed Moustapha TCHOUFON', ('9', '0'), 'Abdelkarim FERGAT', 'by VSU', 'May 2022'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Raby BAPELEKIA', ('0', '0'), 'Abdelkarim FERGAT', 'by VFO', 'May 2022'),
    ('gr', '60 Kg', 'Sailike WALIHAN', 'Abdelkarim FERGAT', ('6', '1'), 'Sailike WALIHAN', 'by VPO1', 'Aug 2021'),
    ('gr', '60 Kg', 'Kenichiro FUMITA', 'Abdelkarim FERGAT', ('8', '0'), 'Kenichiro FUMITA', 'by VSU', 'Aug 2021'),
    ('gr', '60 Kg', 'Michal Jacek TRACZ', 'Abdelkarim FERGAT', ('6', '2'), 'Michal Jacek TRACZ', 'by VPO1', 'Jun 2021'),
    ('gr', '60 Kg', 'Olivier Tomasz SKRZYPCZAK', 'Abdelkarim FERGAT', ('6', '3'), 'Olivier Tomasz SKRZYPCZAK', 'by VFA', 'Jun 2021'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Abdelkarim FERGAT', ('10', '3'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Apr 2021'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Fouad FAJARI', ('5', '3'), 'Abdelkarim FERGAT', 'by VPO1', 'Apr 2021'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Josh FAILAUGA', ('8', '0'), 'Abdelkarim FERGAT', 'by VSU', 'Apr 2021'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Mehdi JOUINI', ('10', '0'), 'Abdelkarim FERGAT', 'by VSU', 'Apr 2021'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Artiom DELEANU', ('6', '4'), 'Abdelkarim FERGAT', 'by VPO1', 'Dec 2020'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Cristian Vasile VAGIUNIC', ('14', '5'), 'Abdelkarim FERGAT', 'by VSU1', 'Dec 2020'),
    ('gr', '60 Kg', 'Serif KILIC', 'Abdelkarim FERGAT', ('10', '0'), 'Serif KILIC', 'by VSU', 'Dec 2020'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Dhia Eddine BAALOUCHI', ('11', '2'), 'Abdelkarim FERGAT', 'by VSU1', 'Feb 2020'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Youssef Mohamed Harbi THABET', ('16', '6'), 'Abdelkarim FERGAT', 'by VSU', 'Feb 2020'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Ismail ETTALIBI', ('6', '0'), 'Abdelkarim FERGAT', 'by VFA', 'Feb 2020'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Romio Ricardo GOLIATH', ('4', '3'), 'Abdelkarim FERGAT', 'by VPO1', 'Feb 2020'),
    ('gr', '60 Kg', 'Max Emiliano NOWRY', 'Abdelkarim FERGAT', ('11', '3'), 'Max Emiliano NOWRY', 'by VSU1', 'Sep 2019'),
    ('gr', '60 Kg', 'Khorlan ZHAKANSHA', 'Abdelkarim FERGAT', ('9', '5'), 'Khorlan ZHAKANSHA', 'by VPO1', 'Sep 2019'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Romio Ricardo GOLIATH', ('8', '0'), 'Abdelkarim FERGAT', 'by VSU', 'Mar 2019'),
    ('gr', '60 Kg', 'Ahmed Fouad Fouad Hussein BAGHDOUDA', 'Abdelkarim FERGAT', ('6', '4'), 'Ahmed Fouad Fouad Hussein BAGHDOUDA', 'by VPO1', 'Mar 2019'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Salim HAMDI', ('0', '0'), 'Abdelkarim FERGAT', 'by VFO', 'Mar 2019'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Jozsef ANDRASI', ('9', '0'), 'Abdelkarim FERGAT', 'by VSU', 'Feb 2019'),
    ('gr', '60 Kg', 'Javokhir MIRAKHMEDOV', 'Abdelkarim FERGAT', ('11', '6'), 'Javokhir MIRAKHMEDOV', 'by VPO1', 'Feb 2019'),
    ('gr', '60 Kg', 'Ilkhom BAKHROMOV', 'Abdelkarim FERGAT', ('6', '4'), 'Ilkhom BAKHROMOV', 'by VPO1', 'Feb 2019'),
    ('gr', '60 Kg', 'Reza Kheirollah KHEDRI', 'Abdelkarim FERGAT', ('8', '0'), 'Reza Kheirollah KHEDRI', 'by VSU', 'Feb 2019'),
    ('gr', '60 Kg', 'Sargis KHACHATRYAN', 'Abdelkarim FERGAT', ('5', '3'), 'Sargis KHACHATRYAN', 'by VPO1', 'Oct 2018'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Tamas TOEROEK', ('14', '7'), 'Abdelkarim FERGAT', 'by VPO1', 'Jun 2018'),
    ('gr', '60 Kg', 'Zhanserik SARSENBIYEV', 'Abdelkarim FERGAT', ('11', '2'), 'Zhanserik SARSENBIYEV', 'by VSU1', 'Jun 2018'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Marat GARIPOV', ('9', '5'), 'Abdelkarim FERGAT', 'by VPO1', 'Jun 2018'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Mahmoud Hussein Hemdan HUSSEIN', ('5', '1'), 'Abdelkarim FERGAT', 'by VPO1', 'Feb 2018'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Henry James AKINWALE', ('6', '0'), 'Abdelkarim FERGAT', 'by VFA', 'Feb 2018'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Given SIKHOSANA', ('10', '0'), 'Abdelkarim FERGAT', 'by VFA', 'Feb 2018'),
    ('gr', '60 Kg', 'Abdelkarim FERGAT', 'Abderrazak ROUINBI', ('0', '0'), 'Abdelkarim FERGAT', 'by DSQ', 'Feb 2018'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Mohamed Yacine DRIDI', ('8', '1'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Mar 2024'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Given SIKHOSANA', ('0', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VIN', 'Mar 2024'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Mohamed Yacine DRIDI', ('8', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Mar 2024'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Ibrahim BUNDUKA', ('9', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Mar 2024'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('10', '1'), 'Islomjon BAKHRAMOV', 'by VSU1', 'Sep 2023'),
    ('gr', '60 Kg', 'Hanjae CHUNG', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('4', '0'), 'Hanjae CHUNG', 'by VPO', 'Jul 2023'),
    ('gr', '60 Kg', 'Kerem KAMAL', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('9', '0'), 'Kerem KAMAL', 'by VSU', 'Jul 2023'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Ibrahim BUNDUKA', ('12', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'May 2023'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Sefiane GUEZZANIA', ('7', '1'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'May 2023'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Ismail ETTALIBI', ('7', '6'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'May 2023'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Haodong TAN', ('7', '3'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Feb 2023'),
    ('gr', '60 Kg', 'Yernar FIDAKHMETOV', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('11', '8'), 'Yernar FIDAKHMETOV', 'by VPO1', 'Feb 2023'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Nursultan BAZARBAYEV', ('5', '4'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Feb 2023'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Vikram Krushnath KURADE', ('5', '4'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Feb 2023'),
    ('gr', '60 Kg', 'Justas PETRAVICIUS', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('11', '1'), 'Justas PETRAVICIUS', 'by VSU1', 'Sep 2022'),
    ('gr', '60 Kg', 'Edmond Armen NAZARYAN', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('2', '1'), 'Edmond Armen NAZARYAN', 'by VPO1', 'Sep 2022'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Kevin Yuran DE ARMAS RODRIGUEZ', ('12', '2'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU1', 'Sep 2022'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Ivan LIZATOVIC', ('3', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO', 'Jun 2022'),
    ('gr', '60 Kg', 'Kerem KAMAL', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('7', '4'), 'Kerem KAMAL', 'by VPO1', 'Jun 2022'),
    ('gr', '60 Kg', 'Sergey EMELIN', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('7', '6'), 'Sergey EMELIN', 'by VPO1', 'Aug 2021'),
    ('gr', '60 Kg', 'Ekrem OZTURK', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('9', '0'), 'Ekrem OZTURK', 'by VSU', 'Jun 2021'),
    ('gr', '60 Kg', 'Mukhammadkodir YUSUPOV', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('4', '2'), 'Mukhammadkodir YUSUPOV', 'by VPO1', 'Jun 2021'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Abdelkarim FERGAT', ('10', '3'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Apr 2021'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Mehdi JOUINI', ('9', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Apr 2021'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Romio Ricardo GOLIATH', ('8', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Apr 2021'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Fouad FAJARI', ('3', '1'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Apr 2021'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Mehdi DHEKER', ('2', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO', 'Feb 2020'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Abderrazak ROUINBI', ('9', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Feb 2020'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Abdennour LAOUNI', ('2', '1'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Feb 2020'),
    ('gr', '60 Kg', 'Kerem KAMAL', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('9', '0'), 'Kerem KAMAL', 'by VSU', 'Jan 2020'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Giovanni FRENI', ('10', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Jan 2020'),
    ('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('3', '1'), 'Ali Reza Ayat Ollah NEJATI', 'by VPO1', 'Sep 2019'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Dicther Hans TORO CASTANEDA', ('6', '4'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Sep 2019'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Fouad FAJARI', ('1', '1'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Aug 2019'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Jonathan Ngeta IBANDA', ('9', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Aug 2019'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Fouad FAJARI', ('3', '1'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Aug 2019'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Kenneth KOECH', ('4', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VFA', 'Aug 2019'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Radhwen TARHOUNI', ('8', '1'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VFA', 'Mar 2019'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Gert Cornelius Johannes COETZEE', ('9', '1'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU1', 'Mar 2019'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Abdeldjebar DJEBBARI', ('3', '2'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Mar 2019'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Fouad FAJARI', ('5', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO', 'Mar 2019'),
    ('gr', '60 Kg', 'Mustafa SAGLAM', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('7', '2'), 'Mustafa SAGLAM', 'by VPO1', 'Feb 2019'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Avgustin Boyanov SPASOV', ('8', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Feb 2019'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Victor CIOBANU', ('11', '2'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU1', 'Feb 2019'),
    ('gr', '60 Kg', 'Maksim KAZHARSKI', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('5', '1'), 'Maksim KAZHARSKI', 'by VPO1', 'Oct 2018'),
    ('gr', '60 Kg', 'Sergey EMELIN', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Oct 2018'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Ivo Serafimov ANGELOV', ('7', '2'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Oct 2018'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Billel BENBRIH', ('7', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO', 'Apr 2016'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'El Mahadi MESSAOUDI', ('8', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Apr 2016'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Hleb MAKARANKA', ('7', '1'), 'Victor CIOBANU', 'by VPO1', 'Apr 2024'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Justas PETRAVICIUS', ('14', '0'), 'Victor CIOBANU', 'by VSU', 'Apr 2024'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Melkamu FETENE', ('11', '0'), 'Victor CIOBANU', 'by VSU', 'Apr 2024'),
    ('gr', '60 Kg', 'Nihat Zahid MAMMADLI', 'Victor CIOBANU', ('8', '3'), 'Nihat Zahid MAMMADLI', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Sadyk LALAEV', ('5', '3'), 'Victor CIOBANU', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Georgij TIBILOV', ('8', '0'), 'Victor CIOBANU', 'by VSU', 'Feb 2024'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Viktor PETRYK', ('12', '3'), 'Victor CIOBANU', 'by VSU1', 'Feb 2024'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Victor CIOBANU', ('0', '0'), 'Sadyk LALAEV', 'by VIN', 'Jan 2024'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Edmond Armen NAZARYAN', ('3', '3'), 'Victor CIOBANU', 'by VPO1', 'Jan 2024'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Ildar HAFIZOV', ('9', '1'), 'Victor CIOBANU', 'by VFA', 'Jan 2024'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Leo Alexandre Sylvain TUDEZCA', ('9', '0'), 'Victor CIOBANU', 'by VSU', 'Jan 2024'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Hassan Mohammed H ALHARTHI', ('8', '4'), 'Victor CIOBANU', 'by VPO1', 'Jan 2024'),
    ('gr', '60 Kg', 'Liguo CAO', 'Victor CIOBANU', ('9', '7'), 'Liguo CAO', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Manish MANISH', ('9', '0'), 'Victor CIOBANU', 'by VSU', 'Sep 2023'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Helary MAEGISALU', ('5', '3'), 'Victor CIOBANU', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Kenichiro FUMITA', 'Victor CIOBANU', ('3', '1'), 'Kenichiro FUMITA', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Justas PETRAVICIUS', ('6', '3'), 'Victor CIOBANU', 'by VFA', 'Jul 2023'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Xavier Tramain JOHNSON', ('14', '4'), 'Victor CIOBANU', 'by VFA', 'Jul 2023'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Victor CIOBANU', ('9', '0'), 'Murad MAMMADOV', 'by VSU', 'Jul 2023'),
    ('gr', '60 Kg', 'Edmond Armen NAZARYAN', 'Victor CIOBANU', ('13', '0'), 'Edmond Armen NAZARYAN', 'by VSU', 'Apr 2023'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Georgij TIBILOV', ('5', '2'), 'Victor CIOBANU', 'by VPO1', 'Apr 2023'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Kerem KAMAL', ('17', '8'), 'Victor CIOBANU', 'by VFA', 'Apr 2023'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Leo Alexandre Sylvain TUDEZCA', ('8', '0'), 'Victor CIOBANU', 'by VSU', 'Apr 2023'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Christopher Josef KRAEMER', ('10', '5'), 'Victor CIOBANU', 'by VPO1', 'Apr 2023'),
    ('gr', '60 Kg', 'Syimyk Makhamadzhanovich MAKHMUDOV', 'Victor CIOBANU', ('11', '4'), 'Syimyk Makhamadzhanovich MAKHMUDOV', 'by VFA', 'Feb 2023'),
    ('gr', '60 Kg', 'Meysam Karamali DALKHANI', 'Victor CIOBANU', ('4', '0'), 'Meysam Karamali DALKHANI', 'by VPO', 'Feb 2023'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Ismail ETTALIBI', ('8', '0'), 'Victor CIOBANU', 'by VSU', 'Feb 2023'),
    ('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Victor CIOBANU', ('5', '3'), 'Ali Reza Ayat Ollah NEJATI', 'by VPO1', 'Sep 2022'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Aker SCHMID AL OBAIDI', ('9', '0'), 'Victor CIOBANU', 'by VSU', 'Sep 2022'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Jinseub SONG', ('5', '3'), 'Victor CIOBANU', 'by VPO1', 'Sep 2022'),
    ('gr', '60 Kg', 'Taleh MAMMADOV', 'Victor CIOBANU', ('4', '2'), 'Taleh MAMMADOV', 'by VPO1', 'Jun 2022'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Justas PETRAVICIUS', ('12', '5'), 'Victor CIOBANU', 'by VPO1', 'Jun 2022'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Jesse David THIELKE', ('9', '0'), 'Victor CIOBANU', 'by VSU', 'Jun 2022'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Taleh MAMMADOV', ('7', '0'), 'Victor CIOBANU', 'by VFA', 'Jun 2022'),
    ('gr', '60 Kg', 'Etienne KINSINGER', 'Victor CIOBANU', ('3', '1'), 'Etienne KINSINGER', 'by VPO1', 'Jun 2022'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Perica DIMITRIJEVIC', ('10', '0'), 'Victor CIOBANU', 'by VSU', 'Jun 2022'),
    ('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Victor CIOBANU', ('9', '0'), 'Islomjon BAKHRAMOV', 'by VSU', 'Feb 2022'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Ahmet UYAR', ('10', '0'), 'Victor CIOBANU', 'by VSU', 'Feb 2022'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Justas PETRAVICIUS', ('0', '0'), 'Victor CIOBANU', 'by VIN', 'Feb 2022'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Abdurrahman ALTAN', ('0', '1'), 'Victor CIOBANU', 'by VPO1', 'Feb 2022'),
    ('gr', '60 Kg', 'Sergey EMELIN', 'Victor CIOBANU', ('5', '2'), 'Sergey EMELIN', 'by VPO1', 'Dec 2021'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Zholaman SHARSHENBEKOV', ('9', '3'), 'Victor CIOBANU', 'by VPO1', 'Oct 2021'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Gevorg GHARIBYAN', ('9', '6'), 'Victor CIOBANU', 'by VPO1', 'Oct 2021'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Stepan MARYANYAN', ('7', '6'), 'Victor CIOBANU', 'by VPO1', 'Oct 2021'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Zhora ABOVIAN', ('11', '6'), 'Victor CIOBANU', 'by VPO1', 'Oct 2021'),
    ('gr', '60 Kg', 'Sergey EMELIN', 'Victor CIOBANU', ('12', '1'), 'Sergey EMELIN', 'by VSU1', 'Aug 2021'),
    ('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Victor CIOBANU', ('11', '0'), 'Luis Alberto ORTA SANCHEZ', 'by VSU', 'Aug 2021'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Zholaman SHARSHENBEKOV', ('9', '0'), 'Victor CIOBANU', 'by VSU', 'Aug 2021'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Kerem KAMAL', ('8', '0'), 'Victor CIOBANU', 'by VSU', 'Aug 2021'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Armen MELIKYAN', ('0', '0'), 'Victor CIOBANU', 'by VIN', 'May 2021'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Dato CHKHARTISHVILI', ('2', '1'), 'Victor CIOBANU', 'by VFA', 'May 2021'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Firuz MIRZORAJABOV', ('14', '0'), 'Victor CIOBANU', 'by VCA', 'May 2021'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Helary MAEGISALU', ('8', '5'), 'Victor CIOBANU', 'by VPO1', 'May 2021'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Fouad FAJARI', ('0', '0'), 'Victor CIOBANU', 'by VFO', 'May 2021'),
    ('gr', '60 Kg', 'Irakli DZIMISTARISHVILI', 'Victor CIOBANU', ('9', '0'), 'Irakli DZIMISTARISHVILI', 'by VSU', 'Mar 2021'),
    ('gr', '60 Kg', 'Kerem KAMAL', 'Victor CIOBANU', ('9', '1'), 'Kerem KAMAL', 'by VSU1', 'Mar 2021'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Soslan DAUROV', ('7', '2'), 'Victor CIOBANU', 'by VPO1', 'Mar 2021'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Niklas OHLEN', ('8', '7'), 'Victor CIOBANU', 'by VPO1', 'Jan 2021'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Stig Andre BERGE', ('10', '0'), 'Victor CIOBANU', 'by VSU', 'Jan 2021'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Andrej GINC', ('7', '2'), 'Victor CIOBANU', 'by VPO1', 'Jan 2021'),
    ('gr', '60 Kg', 'Maksim KAZHARSKI', 'Victor CIOBANU', ('3', '1'), 'Maksim KAZHARSKI', 'by VPO1', 'Dec 2020'),
    ('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Victor CIOBANU', ('8', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Dec 2020'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Nihat Zahid MAMMADLI', ('7', '0'), 'Victor CIOBANU', 'by VPO', 'Dec 2020'),
    ('gr', '60 Kg', 'Erik TORBA', 'Victor CIOBANU', ('10', '3'), 'Erik TORBA', 'by VPO1', 'Feb 2020'),
    ('gr', '60 Kg', 'Elmurat TASMURADOV', 'Victor CIOBANU', ('9', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Sep 2019'),
    ('gr', '60 Kg', 'Kenichiro FUMITA', 'Victor CIOBANU', ('12', '5'), 'Kenichiro FUMITA', 'by VPO1', 'Sep 2019'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Manish MANISH', ('10', '0'), 'Victor CIOBANU', 'by VSU', 'Sep 2019'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Helary MAEGISALU', ('6', '1'), 'Victor CIOBANU', 'by VPO1', 'Sep 2019'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Zhora ABOVIAN', ('3', '1'), 'Victor CIOBANU', 'by VPO1', 'Jun 2019'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Kerem KAMAL', ('10', '9'), 'Victor CIOBANU', 'by VPO1', 'Jun 2019'),
    ('gr', '60 Kg', 'Stepan MARYANYAN', 'Victor CIOBANU', ('9', '1'), 'Stepan MARYANYAN', 'by VSU1', 'Jun 2019'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Sergey EMELIN', ('5', '5'), 'Victor CIOBANU', 'by VPO1', 'Apr 2019'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Lenur TEMIROV', ('6', '4'), 'Victor CIOBANU', 'by VPO1', 'Apr 2019'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Avgustin Boyanov SPASOV', ('10', '0'), 'Victor CIOBANU', 'by VSU', 'Apr 2019'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Ivan LIZATOVIC', ('3', '1'), 'Victor CIOBANU', 'by VPO1', 'Apr 2019'),
    ('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Victor CIOBANU', ('11', '2'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU1', 'Feb 2019'),
    ('gr', '60 Kg', 'Sergey EMELIN', 'Victor CIOBANU', ('10', '1'), 'Sergey EMELIN', 'by VSU1', 'Oct 2018'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Kristian FRIS', ('6', '3'), 'Victor CIOBANU', 'by VPO1', 'Oct 2018'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Sailike WALIHAN', ('6', '6'), 'Victor CIOBANU', 'by VPO1', 'Oct 2018'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Etienne KINSINGER', ('8', '1'), 'Victor CIOBANU', 'by VPO1', 'Oct 2018'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Erik TORBA', ('3', '3'), 'Victor CIOBANU', 'by VPO1', 'Oct 2018'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Victor CIOBANU', ('0', '0'), 'Aidos SULTANGALI', 'by VIN', 'Jul 2018'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Sakit GULIYEV', ('10', '5'), 'Victor CIOBANU', 'by VPO1', 'Jul 2018'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Gyanender GYANENDER', ('7', '0'), 'Victor CIOBANU', 'by VPO', 'Jul 2018'),
    ('gr', '60 Kg', 'Armen MELIKYAN', 'Victor CIOBANU', ('8', '7'), 'Armen MELIKYAN', 'by VPO1', 'Apr 2018'),
    ('gr', '60 Kg', 'Taleh MAMMADOV', 'Victor CIOBANU', ('12', '9'), 'Taleh MAMMADOV', 'by VPO1', 'Aug 2017'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Leo Alexandre Sylvain TUDEZCA', ('7', '5'), 'Victor CIOBANU', 'by VPO1', 'Aug 2017'),
    ('gr', '60 Kg', 'Revaz LASHKHI', 'Victor CIOBANU', ('6', '1'), 'Revaz LASHKHI', 'by VPO1', 'Apr 2016'),
    ('gr', '60 Kg', 'Stig-Andre BERGE', 'Victor CIOBANU', ('1', '1'), 'Stig-Andre BERGE', 'by VPO1', 'Apr 2016'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Erhan Turan KARAKUS', ('7', '3'), 'Victor CIOBANU', 'by VPO1', 'Apr 2016'),
    ('gr', '60 Kg', 'Roman AMOYAN', 'Victor CIOBANU', ('8', '2'), 'Roman AMOYAN', 'by VPO1', 'Sep 2015'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Zaur KABOLEV', ('5', '3'), 'Victor CIOBANU', 'by VPO1', 'Mar 2015'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Eldaniz AZIZLI', ('6', '2'), 'Victor CIOBANU', 'by VPO1', 'Mar 2015'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Vazgen KHACHATRYAN', ('3', '2'), 'Victor CIOBANU', 'by VPO1', 'Mar 2015'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Tamas NADJ', ('10', '0'), 'Victor CIOBANU', 'by VSU', 'Mar 2015'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Nikola VICHEV', ('7', '0'), 'Victor CIOBANU', 'by VFA', 'Mar 2015'),
    ('gr', '60 Kg', 'Deniz MENEKSE', 'Victor CIOBANU', ('6', '2'), 'Deniz MENEKSE', 'by VFA', 'Sep 2014'),
    ('gr', '60 Kg', 'Enes BASAR', 'Anvar ALLAKHIAROV', ('5', '2'), 'Enes BASAR', 'by VPO1', 'Apr 2024'),
    ('gr', '60 Kg', 'Enes BASAR', 'Nihat Zahid MAMMADLI', ('3', '1'), 'Enes BASAR', 'by VPO1', 'Apr 2024'),
    ('gr', '60 Kg', 'Enes BASAR', 'Etienne KINSINGER', ('5', '3'), 'Enes BASAR', 'by VPO1', 'Apr 2024'),
    ('gr', '60 Kg', 'Enes BASAR', 'Georgij TIBILOV', ('9', '0'), 'Enes BASAR', 'by VSU', 'Apr 2024'),
    ('gr', '60 Kg', 'Anvar ALLAKHIAROV', 'Enes BASAR', ('10', '9'), 'Anvar ALLAKHIAROV', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Enes BASAR', 'Aker SCHMID AL OBAIDI', ('5', '1'), 'Enes BASAR', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Enes BASAR', 'Stefan Roger CLEMENT', ('9', '6'), 'Enes BASAR', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Enes BASAR', 'Oleksandr HRUSHYN', ('8', '0'), 'Enes BASAR', 'by VSU', 'Sep 2023'),
    ('gr', '60 Kg', 'Leri ABULADZE', 'Enes BASAR', ('4', '3'), 'Leri ABULADZE', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Enes BASAR', 'Ryuto IKEDA', ('9', '0'), 'Enes BASAR', 'by VSU', 'Sep 2023'),
    ('gr', '60 Kg', 'Almat KEBISPAYEV', 'Enes BASAR', ('5', '0'), 'Almat KEBISPAYEV', 'by VFA', 'May 2021'),
    ('gr', '60 Kg', 'Almat KEBISPAYEV', 'Enes BASAR', ('3', '2'), 'Almat KEBISPAYEV', 'by VPO1', 'Mar 2021'),
    ('gr', '60 Kg', 'Enes BASAR', 'Andres Roberto MONTANO ARROYO', ('9', '0'), 'Enes BASAR', 'by VSU', 'Mar 2021'),
    ('gr', '60 Kg', 'Meiirzhan SHERMAKHANBET', 'Enes BASAR', ('9', '0'), 'Meiirzhan SHERMAKHANBET', 'by VSU', 'Mar 2021'),
    ('gr', '60 Kg', 'Enes BASAR', 'Krisztian Istvan VANCZA', ('9', '5'), 'Enes BASAR', 'by VPO1', 'Mar 2021'),
    ('gr', '60 Kg', 'Haci KARAKUS', 'Enes BASAR', ('10', '7'), 'Haci KARAKUS', 'by VPO1', 'Jan 2021'),
    ('gr', '60 Kg', 'Gevorg SAHAKYAN', 'Enes BASAR', ('9', '0'), 'Gevorg SAHAKYAN', 'by VSU', 'Jan 2021'),
    ('gr', '60 Kg', 'Enes BASAR', 'Daniel SOINI', ('6', '1'), 'Enes BASAR', 'by VPO1', 'Jan 2021'),
    ('gr', '60 Kg', 'Enes BASAR', 'Ruben MARVICE', ('11', '4'), 'Enes BASAR', 'by VPO1', 'Jan 2021'),
    ('gr', '60 Kg', 'Kristupas SLEIVA', 'Enes BASAR', ('10', '0'), 'Kristupas SLEIVA', 'by VSU', 'Feb 2020'),
    ('gr', '60 Kg', 'Morten THORESEN', 'Enes BASAR', ('2', '0'), 'Morten THORESEN', 'by VPO', 'Feb 2020'),
    ('gr', '60 Kg', 'Enes BASAR', 'Ott SAAR', ('10', '1'), 'Enes BASAR', 'by VSU1', 'Feb 2020'),
    ('gr', '60 Kg', 'Maksim NEHODA', 'Enes BASAR', ('8', '0'), 'Maksim NEHODA', 'by VSU', 'Jul 2019'),
    ('gr', '60 Kg', 'Oleksii KALINICHENKO', 'Enes BASAR', ('5', '0'), 'Oleksii KALINICHENKO', 'by VFA', 'Jun 2019'),
    ('gr', '60 Kg', 'Enes BASAR', 'Mateusz Lucjan BERNATEK', ('7', '5'), 'Enes BASAR', 'by VPO1', 'Jun 2019'),
    ('gr', '60 Kg', 'Mate KRASZNAI', 'Enes BASAR', ('3', '2'), 'Mate KRASZNAI', 'by VPO1', 'Feb 2019'),
    ('gr', '60 Kg', 'Enes BASAR', 'Qiye TIAN', ('7', '3'), 'Enes BASAR', 'by VIN', 'Feb 2019'),
    ('gr', '60 Kg', 'Enes BASAR', 'Morten THORESEN', ('9', '0'), 'Enes BASAR', 'by VSU', 'Feb 2019'),
    ('gr', '60 Kg', 'Elmurat TASMURADOV', 'Enes BASAR', ('13', '4'), 'Elmurat TASMURADOV', 'by VSU1', 'Feb 2019'),
    ('gr', '60 Kg', 'Enes BASAR', 'Danielo Giuseppe DI FEOLA', ('5', '3'), 'Enes BASAR', 'by VPO1', 'Feb 2019'),
    ('gr', '60 Kg', 'Enes BASAR', 'Mate KRASZNAI', ('9', '1'), 'Enes BASAR', 'by VSU1', 'Feb 2019'),
    ('gr', '60 Kg', 'Amantur ISMAILOV', 'Enes BASAR', ('7', '5'), 'Amantur ISMAILOV', 'by VPO1', 'Jul 2018'),
    ('gr', '60 Kg', 'Enes BASAR', 'Fredrik Holmquist BJERREHUUS', ('5', '4'), 'Enes BASAR', 'by VPO1', 'Apr 2018'),
    ('gr', '60 Kg', 'Enes BASAR', 'Edgaras VENCKAITIS', ('5', '3'), 'Enes BASAR', 'by VPO1', 'Apr 2018'),
    ('gr', '60 Kg', 'Shmagi BOLKVADZE', 'Enes BASAR', ('6', '0'), 'Shmagi BOLKVADZE', 'by VPO', 'Apr 2018'),
    ('gr', '60 Kg', 'Ismael BORRERO MOLINA', 'Enes BASAR', ('9', '0'), 'Ismael BORRERO MOLINA', 'by VSU', 'Jan 2018'),
    ('gr', '60 Kg', 'Enes BASAR', 'Yaraslau KARDASH', ('0', '0'), 'Enes BASAR', 'by VFO', 'Mar 2017'),
    ('gr', '60 Kg', 'Enes BASAR', 'Otto LOSONCZI', ('9', '1'), 'Enes BASAR', 'by VPO1', 'Mar 2015'),
    ('gr', '60 Kg', 'Enes BASAR', 'Rovhsan TAGHIYEV', ('7', '4'), 'Enes BASAR', 'by VFA', 'Mar 2015'),
    ('gr', '60 Kg', 'Artem SURKOV', 'Enes BASAR', ('8', '0'), 'Artem SURKOV', 'by VSU', 'Mar 2015'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Jui Chi HUANG', ('10', '0'), 'Aidos SULTANGALI', 'by VFA', 'Apr 2024'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Aslamjon AZIZOV', ('2', '1'), 'Aidos SULTANGALI', 'by VPO1', 'Apr 2024'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Sajjad Ali Mukasr ALBIDHAN', ('9', '0'), 'Aidos SULTANGALI', 'by VSU', 'Apr 2024'),
    ('gr', '60 Kg', 'Se Ung RI', 'Aidos SULTANGALI', ('2', '1'), 'Se Ung RI', 'by VPO1', 'Oct 2023'),
    ('gr', '60 Kg', 'Ayata SUZUKI', 'Aidos SULTANGALI', ('9', '0'), 'Ayata SUZUKI', 'by VSU', 'Oct 2023'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Meysam Karamali DALKHANI', ('4', '2'), 'Aidos SULTANGALI', 'by VPO1', 'Oct 2023'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Jui Chi HUANG', ('11', '1'), 'Aidos SULTANGALI', 'by VSU1', 'Oct 2023'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Mukremin AKTAS', ('7', '1'), 'Aidos SULTANGALI', 'by VPO1', 'Nov 2022'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Murad MAMMADOV', ('4', '1'), 'Aidos SULTANGALI', 'by VFA', 'Nov 2022'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'FFT FFT', ('0', '0'), 'Aidos SULTANGALI', 'by VFO', 'Nov 2022'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Krisztian KECSKEMETI', ('7', '1'), 'Aidos SULTANGALI', 'by VPO1', 'Sep 2022'),
    ('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Aidos SULTANGALI', ('7', '0'), 'Zholaman SHARSHENBEKOV', 'by VPO', 'Sep 2022'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Liguo CAO', ('7', '1'), 'Aidos SULTANGALI', 'by VPO1', 'Sep 2022'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Gevorg GHARIBYAN', ('3', '0'), 'Aidos SULTANGALI', 'by VFA', 'Sep 2022'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Alexandru TRANDAFIR', ('9', '0'), 'Aidos SULTANGALI', 'by VFA', 'Sep 2022'),
    ('gr', '60 Kg', 'Ahmet UYAR', 'Aidos SULTANGALI', ('5', '1'), 'Ahmet UYAR', 'by VPO1', 'Feb 2022'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Sagar SAGAR', ('5', '0'), 'Aidos SULTANGALI', 'by VFA', 'Feb 2022'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Aidos SULTANGALI', ('6', '1'), 'Murad MAMMADOV', 'by VPO1', 'Oct 2021'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Mehdi Seifollah MOHSEN NEJAD', ('8', '4'), 'Aidos SULTANGALI', 'by VPO1', 'Apr 2021'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Karrar Abbas Mukasr ALBIDHAN', ('7', '2'), 'Aidos SULTANGALI', 'by VPO1', 'Apr 2021'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Seunghak KIM', ('10', '1'), 'Aidos SULTANGALI', 'by VSU1', 'Apr 2021'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Sultan ASSETULY', ('0', '0'), 'Aidos SULTANGALI', 'by VIN', 'Mar 2021'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Marat Maksumovitch GARIPOV', ('1', '0'), 'Aidos SULTANGALI', 'by VIN', 'Mar 2021'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Mohammad F Kh M J ALAJMI', ('12', '3'), 'Aidos SULTANGALI', 'by VSU1', 'Mar 2021'),
    ('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Aidos SULTANGALI', ('4', '3'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VPO1', 'Feb 2020'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Davaabandi MUNKH ERDENE', ('8', '0'), 'Aidos SULTANGALI', 'by VSU', 'Feb 2020'),
    ('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Aidos SULTANGALI', ('7', '6'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Feb 2020'),
    ('gr', '60 Kg', 'Aliaksandr PECHURENKA', 'Aidos SULTANGALI', ('0', '0'), 'Aliaksandr PECHURENKA', 'by VIN', 'Jul 2019'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Se Ung RI', ('1', '1'), 'Aidos SULTANGALI', 'by VPO1', 'Oct 2018'),
    ('gr', '60 Kg', 'Sergey EMELIN', 'Aidos SULTANGALI', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Oct 2018'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Kaly SULAIMANOV', ('9', '1'), 'Aidos SULTANGALI', 'by VSU1', 'Oct 2018'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Shinobu OTA', ('7', '5'), 'Aidos SULTANGALI', 'by VPO1', 'Oct 2018'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Dmytro TSYMBALIUK', ('6', '1'), 'Aidos SULTANGALI', 'by VPO1', 'Oct 2018'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Victor CIOBANU', ('0', '0'), 'Aidos SULTANGALI', 'by VIN', 'Jul 2018'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Avgustin Boyanov SPASOV', ('10', '4'), 'Aidos SULTANGALI', 'by VPO1', 'Jul 2018'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Shimizu HAYANOBU', ('6', '2'), 'Aidos SULTANGALI', 'by VPO1', 'Jul 2018'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Hasan Zahid MAMMADLI', ('4', '1'), 'Aidos SULTANGALI', 'by VPO1', 'Jul 2018'),
    ('gr', '60 Kg', 'Shirzad Ali BEHESHTITALA', 'Aidos SULTANGALI', ('2', '2'), 'Shirzad Ali BEHESHTITALA', 'by VPO1', 'Feb 2018'),
    ('gr', '60 Kg', 'Shirzad Ali BEHESHTITALA', 'Aidos SULTANGALI', ('0', '0'), 'Shirzad Ali BEHESHTITALA', 'by VIN', 'Jan 2018'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Viktor PETRYK', ('3', '2'), 'Aidos SULTANGALI', 'by VPO1', 'Jan 2018'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Avgustin Boyanov SPASOV', ('8', '0'), 'Aidos SULTANGALI', 'by VSU', 'Nov 2017'),
    ('gr', '60 Kg', 'Masuto KAWANA', 'Aidos SULTANGALI', ('6', '5'), 'Masuto KAWANA', 'by VPO1', 'Nov 2017'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Erik TORBA', ('5', '4'), 'Aidos SULTANGALI', 'by VPO1', 'Nov 2017'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Dalton James ROBERTS', ('10', '4'), 'Aidos SULTANGALI', 'by VPO1', 'Nov 2017'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Abdennour LAOUNI', ('9', '0'), 'Aidos SULTANGALI', 'by VSU', 'Nov 2017'),
    ('gr', '60 Kg', 'Mehmet Isa CEKER', 'Aidos SULTANGALI', ('6', '4'), 'Mehmet Isa CEKER', 'by VPO1', 'Aug 2016'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Mohammadreza Abdolhamid GERAEI', ('8', '1'), 'Aidos SULTANGALI', 'by VFA', 'Aug 2016'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Dahyun KIM', ('8', '0'), 'Sadyk LALAEV', 'by VSU', 'May 2024'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Georgij TIBILOV', ('6', '2'), 'Sadyk LALAEV', 'by VPO1', 'May 2024'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Munkh Erdene BATKHUYAG', ('9', '0'), 'Sadyk LALAEV', 'by VSU', 'May 2024'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Georgij TIBILOV', ('2', '1'), 'Sadyk LALAEV', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Sadyk LALAEV', ('5', '3'), 'Victor CIOBANU', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Hleb MAKARANKA', ('2', '0'), 'Sadyk LALAEV', 'by VPO', 'Feb 2024'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Pridon ABULADZE', ('4', '1'), 'Sadyk LALAEV', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Victor CIOBANU', ('0', '0'), 'Sadyk LALAEV', 'by VIN', 'Jan 2024'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Ihor KUROCHKIN', ('10', '1'), 'Sadyk LALAEV', 'by VSU1', 'Jan 2024'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Anvar ALLAKHIAROV', ('3', '1'), 'Sadyk LALAEV', 'by VPO1', 'Jan 2024'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Hleb MAKARANKA', ('5', '3'), 'Sadyk LALAEV', 'by VPO1', 'Jan 2024'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Munthir Abdullah A JANDU', ('7', '1'), 'Sadyk LALAEV', 'by VPO1', 'Jan 2024'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Rakhmatsikhudo KHAIBARAU', ('9', '0'), 'Sadyk LALAEV', 'by VSU', 'Jul 2019'),
    ('gr', '60 Kg', 'Seunghak KIM', 'Sadyk LALAEV', ('5', '0'), 'Seunghak KIM', 'by VPO', 'Jul 2019'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Khorlan ZHAKANSHA', ('11', '3'), 'Sadyk LALAEV', 'by VSU1', 'Jul 2019'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Kanstantsin DZIVACHENKA', ('11', '0'), 'Sadyk LALAEV', 'by VSU', 'Jul 2019'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Irakli DZIMISTARISHVILI', ('7', '0'), 'Sadyk LALAEV', 'by VPO', 'Mar 2019'),
    ('gr', '60 Kg', 'Kerem KAMAL', 'Sadyk LALAEV', ('6', '5'), 'Kerem KAMAL', 'by VPO1', 'Mar 2019'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Eldaniz AZIZLI', ('0', '0'), 'Sadyk LALAEV', 'by VIN', 'Sep 2018'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Zhanserik SARSENBIYEV', ('9', '0'), 'Sadyk LALAEV', 'by VSU', 'Sep 2018'),
    ('gr', '60 Kg', 'Artur Muchegovitch PETROSIAN', 'Sadyk LALAEV', ('10', '0'), 'Artur Muchegovitch PETROSIAN', 'by VCA', 'Sep 2018'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Di HU', ('5', '3'), 'Sadyk LALAEV', 'by VPO1', 'Sep 2018'),
    ('gr', '60 Kg', 'Zhambolat LOKYAEV', 'Sadyk LALAEV', ('8', '1'), 'Zhambolat LOKYAEV', 'by VPO1', 'Jan 2018'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Dmitrii LIUSTRITSKII', ('3', '0'), 'Sadyk LALAEV', 'by VPO', 'Jan 2018'),
    ('gr', '60 Kg', 'Mingiyan SEMENOV', 'Sadyk LALAEV', ('7', '1'), 'Mingiyan SEMENOV', 'by VPO1', 'Jan 2018'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Magomed MAGOMEDOV', ('4', '0'), 'Sadyk LALAEV', 'by VPO', 'Jan 2018'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Razvan ARNAUT', ('8', '2'), 'Murad MAMMADOV', 'by VPO1', 'May 2024'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Michal Jacek TRACZ', ('5', '1'), 'Murad MAMMADOV', 'by VPO1', 'May 2024'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Christopher Josef KRAEMER', ('10', '1'), 'Murad MAMMADOV', 'by VSU1', 'May 2024'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Aleksandrs JURKJANS', ('10', '1'), 'Murad MAMMADOV', 'by VSU1', 'May 2024'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Oleksandr HRUSHYN', ('2', '1'), 'Murad MAMMADOV', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Anvar ALLAKHIAROV', ('3', '3'), 'Murad MAMMADOV', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Aleksandrs JURKJANS', ('3', '1'), 'Murad MAMMADOV', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Brian Kurt SANTIAGO', ('8', '0'), 'Murad MAMMADOV', 'by VSU', 'Feb 2024'),
    ('gr', '60 Kg', 'Jacopo SANDRON', 'Murad MAMMADOV', ('0', '0'), 'Jacopo SANDRON', 'by VIN', 'Jan 2024'),
    ('gr', '60 Kg', 'Virgil Alexander BICA', 'Murad MAMMADOV', ('0', '0'), 'Virgil Alexander BICA', 'by VIN', 'Jan 2024'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Stefan Roger CLEMENT', ('6', '4'), 'Murad MAMMADOV', 'by VPO1', 'Jan 2024'),
    ('gr', '60 Kg', 'Leri ABULADZE', 'Murad MAMMADOV', ('2', '2'), 'Leri ABULADZE', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Georgij TIBILOV', ('4', '1'), 'Murad MAMMADOV', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Hrachya POGHOSYAN', ('3', '1'), 'Murad MAMMADOV', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Xavier Tramain JOHNSON', ('3', '1'), 'Murad MAMMADOV', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Jinwoong JUNG', ('5', '1'), 'Murad MAMMADOV', 'by VPO1', 'Jul 2023'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Justas PETRAVICIUS', ('5', '1'), 'Murad MAMMADOV', 'by VPO1', 'Jul 2023'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Xavier Tramain JOHNSON', ('13', '3'), 'Murad MAMMADOV', 'by VSU1', 'Jul 2023'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Victor CIOBANU', ('9', '0'), 'Murad MAMMADOV', 'by VSU', 'Jul 2023'),
    ('gr', '60 Kg', 'Justas PETRAVICIUS', 'Murad MAMMADOV', ('5', '1'), 'Justas PETRAVICIUS', 'by VPO1', 'Feb 2023'),
    ('gr', '60 Kg', 'Nihat Zahid MAMMADLI', 'Murad MAMMADOV', ('6', '2'), 'Nihat Zahid MAMMADLI', 'by VPO1', 'Feb 2023'),
    ('gr', '60 Kg', 'Aidos SULTANGALI', 'Murad MAMMADOV', ('4', '1'), 'Aidos SULTANGALI', 'by VFA', 'Nov 2022'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'FFT FFT', ('0', '0'), 'Murad MAMMADOV', 'by VFO', 'Nov 2022'),
    ('gr', '60 Kg', 'Kenichiro FUMITA', 'Murad MAMMADOV', ('5', '1'), 'Kenichiro FUMITA', 'by VPO1', 'Sep 2022'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Justas PETRAVICIUS', ('9', '3'), 'Murad MAMMADOV', 'by VPO1', 'Sep 2022'),
    ('gr', '60 Kg', 'Edmond Armen NAZARYAN', 'Murad MAMMADOV', ('2', '1'), 'Edmond Armen NAZARYAN', 'by VPO1', 'Sep 2022'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Rabby Kilonga KILANDI', ('9', '0'), 'Murad MAMMADOV', 'by VSU', 'Sep 2022'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Eldaniz AZIZLI', ('9', '1'), 'Murad MAMMADOV', 'by VSU1', 'Jun 2022'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Helary MAEGISALU', ('9', '4'), 'Murad MAMMADOV', 'by VPO1', 'Jun 2022'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Ildar HAFIZOV', ('9', '0'), 'Murad MAMMADOV', 'by VSU', 'Jun 2022'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Nihat Zahid MAMMADLI', ('7', '1'), 'Murad MAMMADOV', 'by VPO1', 'Jun 2022'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Ekrem OZTURK', ('14', '1'), 'Murad MAMMADOV', 'by VSU1', 'Jun 2022'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Razvan ARNAUT', ('5', '2'), 'Murad MAMMADOV', 'by VPO1', 'Jun 2022'),
    ('gr', '60 Kg', 'Kerem KAMAL', 'Murad MAMMADOV', ('8', '0'), 'Kerem KAMAL', 'by VFA', 'Jun 2022'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Vitalie ERIOMENCO', ('6', '1'), 'Murad MAMMADOV', 'by VPO1', 'Jun 2022'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Daniel BOBILLO VIGIL', ('8', '0'), 'Murad MAMMADOV', 'by VSU', 'Jun 2022'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Maksim KAZHARSKI', ('2', '0'), 'Murad MAMMADOV', 'by VPO', 'Oct 2021'),
    ('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Murad MAMMADOV', ('4', '2'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Oct 2021'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Ayata SUZUKI', ('5', '1'), 'Murad MAMMADOV', 'by VFA', 'Oct 2021'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Aidos SULTANGALI', ('6', '1'), 'Murad MAMMADOV', 'by VPO1', 'Oct 2021'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Krisztian KECSKEMETI', ('3', '0'), 'Murad MAMMADOV', 'by VPO', 'Oct 2021'),
    ('gr', '60 Kg', 'Hanjae CHUNG', 'Murad MAMMADOV', ('2', '1'), 'Hanjae CHUNG', 'by VPO1', 'May 2021'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Maksim KAZHARSKI', ('3', '1'), 'Murad MAMMADOV', 'by VPO1', 'May 2021'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Stig Andre BERGE', ('4', '1'), 'Murad MAMMADOV', 'by VPO1', 'May 2021'),
    ('gr', '60 Kg', 'Ivan LIZATOVIC', 'Murad MAMMADOV', ('0', '0'), 'Ivan LIZATOVIC', 'by VIN', 'Mar 2021'),
    ('gr', '60 Kg', 'Etienne KINSINGER', 'Murad MAMMADOV', ('5', '3'), 'Etienne KINSINGER', 'by VPO1', 'Mar 2021'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Gevorg GHARIBYAN', ('5', '1'), 'Murad MAMMADOV', 'by VPO1', 'Mar 2021'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Justas PETRAVICIUS', ('7', '4'), 'Murad MAMMADOV', 'by VPO1', 'Mar 2021'),
    ('gr', '60 Kg', 'Lenur TEMIROV', 'Murad MAMMADOV', ('10', '5'), 'Lenur TEMIROV', 'by VPO1', 'Apr 2019'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Dawid Andrzej ERSETIC', ('9', '0'), 'Murad MAMMADOV', 'by VSU', 'Apr 2019'),
    ('gr', '60 Kg', 'Ahmet UYAR', 'Murad MAMMADOV', ('4', '3'), 'Ahmet UYAR', 'by VPO1', 'Feb 2019'),
    ('gr', '60 Kg', 'Kenichiro FUMITA', 'Murad MAMMADOV', ('10', '1'), 'Kenichiro FUMITA', 'by VFA', 'Nov 2018'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Kerem KAMAL', ('5', '2'), 'Murad MAMMADOV', 'by VPO1', 'Nov 2018'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Dato CHKHARTISHVILI', ('5', '4'), 'Murad MAMMADOV', 'by VPO1', 'Nov 2018'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Rustam TEIISHOV', ('4', '1'), 'Murad MAMMADOV', 'by VPO1', 'Nov 2018'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Islomjon BAKHRAMOV', ('8', '0'), 'Murad MAMMADOV', 'by VSU', 'Nov 2018'),
    ('gr', '60 Kg', 'Kaly SULAIMANOV', 'Murad MAMMADOV', ('5', '8'), 'Kaly SULAIMANOV', 'by VFA', 'Oct 2018'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Artur Muchegovitch PETROSIAN', ('7', '0'), 'Murad MAMMADOV', 'by VPO', 'Sep 2018'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Ivan LIZATOVIC', ('9', '0'), 'Murad MAMMADOV', 'by VSU', 'Sep 2018'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Rinat BALTASHEV', ('8', '0'), 'Murad MAMMADOV', 'by VSU', 'Sep 2018'),
    ('gr', '60 Kg', 'Dmytro TSYMBALIUK', 'Murad MAMMADOV', ('5', '1'), 'Dmytro TSYMBALIUK', 'by VPO1', 'Jul 2018'),
    ('gr', '60 Kg', 'Taleh MAMMADOV', 'Murad MAMMADOV', ('5', '1'), 'Taleh MAMMADOV', 'by VPO1', 'Jul 2018'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Teodor HORATAU', ('8', '3'), 'Murad MAMMADOV', 'by VPO1', 'Jun 2018'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Avgustin Boyanov SPASOV', ('9', '0'), 'Murad MAMMADOV', 'by VSU', 'Jun 2018'),
    ('gr', '60 Kg', 'Kerem KAMAL', 'Murad MAMMADOV', ('5', '2'), 'Kerem KAMAL', 'by VPO1', 'Jun 2018'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Mikkel LASSEN', ('12', '4'), 'Murad MAMMADOV', 'by VSU1', 'Jun 2018'),
    ('gr', '60 Kg', 'Sergey EMELIN', 'Murad MAMMADOV', ('6', '5'), 'Sergey EMELIN', 'by VPO1', 'Apr 2018'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Jacopo SANDRON', ('9', '0'), 'Murad MAMMADOV', 'by VSU', 'Apr 2018'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Maksim KAZHARSKI', ('3', '0'), 'Murad MAMMADOV', 'by VPO', 'Apr 2018'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Zhambolat LOKYAEV', ('4', '1'), 'Murad MAMMADOV', 'by VPO1', 'Mar 2017'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Abdurrahman ALTAN', ('9', '1'), 'Murad MAMMADOV', 'by VSU1', 'Mar 2017'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Justas PETRAVICIUS', ('8', '0'), 'Murad MAMMADOV', 'by VSU', 'Mar 2017'),
    ('gr', '60 Kg', 'Taleh MAMMADOV', 'Murad MAMMADOV', ('4', '2'), 'Taleh MAMMADOV', 'by VPO1', 'Nov 2016'),
    ('gr', '60 Kg', 'Kenichiro FUMITA', 'Murad MAMMADOV', ('7', '4'), 'Kenichiro FUMITA', 'by VPO1', 'Nov 2016'),
    ('gr', '60 Kg', 'Tsotne ABALAKI', 'Murad MAMMADOV', ('3', '2'), 'Tsotne ABALAKI', 'by VPO1', 'Jul 2016'),
    ('gr', '60 Kg', 'Sergey EMELIN', 'Murad MAMMADOV', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Mar 2016'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Andrey TSARYUK', ('8', '0'), 'Murad MAMMADOV', 'by VSU', 'Mar 2016'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Serif Yakup KILIC', ('7', '2'), 'Murad MAMMADOV', 'by VPO1', 'Mar 2016'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Zoltan LEVAI', ('8', '0'), 'Murad MAMMADOV', 'by VSU', 'Mar 2016'),
    ('gr', '60 Kg', 'Yun WON CHOL', 'Murad MAMMADOV', ('13', '0'), 'Yun WON CHOL', 'by VSU', 'Nov 2015'),
    ('gr', '60 Kg', 'Irakli SHAVADZE', 'Murad MAMMADOV', ('6', '0'), 'Irakli SHAVADZE', 'by VPO', 'Jun 2015'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Slavik GALSTYAN', ('5', '0'), 'Murad MAMMADOV', 'by VFA', 'Jun 2015'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Oleksandr HRUSHYN', ('9', '0'), 'Murad MAMMADOV', 'by VSU', 'Jun 2015'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Erik TORBA', ('9', '7'), 'Murad MAMMADOV', 'by VPO1', 'Jun 2015'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Peter HAASE', ('11', '0'), 'Murad MAMMADOV', 'by VSU', 'Jun 2015'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Andrey TSARYUK', ('9', '0'), 'Murad MAMMADOV', 'by VSU', 'Jan 2015'),
    ('gr', '60 Kg', 'Tarik BELMADANI', 'Murad MAMMADOV', ('9', '0'), 'Tarik BELMADANI', 'by VSU', 'Jan 2015'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Michal TRACZ', ('1', '0'), 'Murad MAMMADOV', 'by VPO', 'Jan 2015'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Ruslan ITEMGENOV', ('11', '0'), 'Murad MAMMADOV', 'by VSU', 'Jan 2015'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Razvan ARNAUT', ('5', '2'), 'Georgij TIBILOV', 'by VPO1', 'May 2024'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Dahyun KIM', ('8', '1'), 'Georgij TIBILOV', 'by VPO1', 'May 2024'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Munkh Erdene BATKHUYAG', ('11', '1'), 'Georgij TIBILOV', 'by VSU1', 'May 2024'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Georgij TIBILOV', ('6', '2'), 'Sadyk LALAEV', 'by VPO1', 'May 2024'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Romio Ricardo GOLIATH', ('8', '0'), 'Georgij TIBILOV', 'by VSU', 'May 2024'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Hleb MAKARANKA', ('10', '1'), 'Georgij TIBILOV', 'by VSU1', 'May 2024'),
    ('gr', '60 Kg', 'Enes BASAR', 'Georgij TIBILOV', ('9', '0'), 'Enes BASAR', 'by VSU', 'Apr 2024'),
    ('gr', '60 Kg', 'Sadyk LALAEV', 'Georgij TIBILOV', ('2', '1'), 'Sadyk LALAEV', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Viktor PETRYK', ('8', '1'), 'Georgij TIBILOV', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Georgij TIBILOV', ('8', '0'), 'Victor CIOBANU', 'by VSU', 'Feb 2024'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Olivier Tomasz SKRZYPCZAK', ('12', '2'), 'Georgij TIBILOV', 'by VSU1', 'Feb 2024'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Kerem KAMAL', ('10', '3'), 'Georgij TIBILOV', 'by VFA', 'Feb 2024'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Aleksandrs JURKJANS', ('9', '1'), 'Georgij TIBILOV', 'by VSU1', 'Jan 2024'),
    ('gr', '60 Kg', 'Leri ABULADZE', 'Georgij TIBILOV', ('5', '5'), 'Leri ABULADZE', 'by VPO1', 'Jan 2024'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Matej REBIC', ('9', '0'), 'Georgij TIBILOV', 'by VSU', 'Jan 2024'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Razvan ARNAUT', ('9', '0'), 'Georgij TIBILOV', 'by VSU', 'Jan 2024'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Hrachya POGHOSYAN', ('4', '0'), 'Georgij TIBILOV', 'by VPO', 'Sep 2023'),
    ('gr', '60 Kg', 'Murad MAMMADOV', 'Georgij TIBILOV', ('4', '1'), 'Murad MAMMADOV', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Ivan LIZATOVIC', ('5', '2'), 'Georgij TIBILOV', 'by VPO1', 'Sep 2023'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Iman Hossein Khoon MOHAMMADI', ('12', '2'), 'Georgij TIBILOV', 'by VSU1', 'Sep 2023'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Mairbek SALIMOV', ('8', '0'), 'Georgij TIBILOV', 'by VSU', 'Sep 2023'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Kerem KAMAL', ('7', '3'), 'Georgij TIBILOV', 'by VPO1', 'Apr 2023'),
    ('gr', '60 Kg', 'Victor CIOBANU', 'Georgij TIBILOV', ('5', '2'), 'Victor CIOBANU', 'by VPO1', 'Apr 2023'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Pridon ABULADZE', ('5', '2'), 'Georgij TIBILOV', 'by VPO1', 'Apr 2023'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Michal Jacek TRACZ', ('5', '0'), 'Georgij TIBILOV', 'by VPO', 'Apr 2023'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Viktor PETRYK', ('9', '1'), 'Georgij TIBILOV', 'by VSU1', 'Apr 2023'),
    ('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Georgij TIBILOV', ('8', '0'), 'Ali Reza Ayat Ollah NEJATI', 'by VSU', 'Nov 2021'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Assaukhat MUKHAMADIYEV', ('4', '0'), 'Georgij TIBILOV', 'by VPO', 'Nov 2021'),
    ('gr', '60 Kg', 'Leri ABULADZE', 'Georgij TIBILOV', ('7', '3'), 'Leri ABULADZE', 'by VPO1', 'Nov 2021'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Kamol KUZIEV', ('3', '1'), 'Georgij TIBILOV', 'by VPO1', 'Nov 2021'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Diego CHKHIKVADZE', ('5', '2'), 'Georgij TIBILOV', 'by VPO1', 'Aug 2019'),
    ('gr', '60 Kg', 'Sahak HOVHANNISYAN', 'Georgij TIBILOV', ('6', '0'), 'Sahak HOVHANNISYAN', 'by VPO', 'Aug 2019'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Myroslav SOLOVIAN', ('8', '0'), 'Georgij TIBILOV', 'by VSU', 'Aug 2019'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Mukhammadkodir YUSUPOV', ('7', '1'), 'Georgij TIBILOV', 'by VPO1', 'Aug 2019'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Ion BACALU', ('11', '2'), 'Georgij TIBILOV', 'by VSU1', 'Aug 2019'),
    ('gr', '60 Kg', 'Emin SEFERSHAEV', 'Georgij TIBILOV', ('5', '1'), 'Emin SEFERSHAEV', 'by VPO1', 'Jan 2018'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Kadir Kazim KAMAL', ('8', '0'), 'Georgij TIBILOV', 'by VSU1', 'Jul 2016'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Guseyn GUSEINOV', ('3', '0'), 'Georgij TIBILOV', 'by VPO', 'Jul 2016'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Ashot MKHITARYAN', ('1', '0'), 'Georgij TIBILOV', 'by VPO', 'Jul 2016'),
    ('gr', '60 Kg', 'Georgij TIBILOV', 'Constantin-Benone LUPU', ('8', '0'), 'Georgij TIBILOV', 'by VSU', 'Jul 2016'),
    ('gr', '60 Kg', 'Hleb MAKARANKA', 'Jamal VALIZADEH', ('3', '1'), 'Hleb MAKARANKA', 'by VPO1', 'Feb 2024'),
    ('gr', '60 Kg', 'Hleb MAKARANKA', 'Jamal VALIZADEH', ('11', '0'), 'Hleb MAKARANKA', 'by VSU', 'Sep 2023'),
    ('gr', '60 Kg', 'Erik TORBA', 'Jamal VALIZADEH', ('9', '0'), 'Erik TORBA', 'by VSU', 'Apr 2023'),
    ]

    return arr
