t_urls_mgr60kg = [#'https://uww.org/athletes-results/fumita-kenichiro-7338-profile',
                      #'https://uww.org/athletes-results/emelin-sergey-6599-profile',
                      #'https://uww.org/athletes-results/ainagulov-mirambek-633-profile',
                      #'https://uww.org/athletes-results/nejati-ali-reza-ayat-ollah-16358-profile',
                      #'https://uww.org/athletes-results/temirov-lenur-22599-profile',
                      #'https://uww.org/athletes-results/tasmuradov-elmurat-22448-profile',
                      #'https://uww.org/athletes-results/orta-sanchez-luis-alberto-17227-profile',
                      #'https://uww.org/athletes-results/hafizov-ildar-8613-profile',
                      #'https://uww.org/athletes-results/kamal-kerem-10729-profile',
                      #'https://uww.org/athletes-results/kinsinger-etienne-11926-profile',
                      #'https://uww.org/athletes-results/mahmoud-haithem-mahmoud-ahmed-fahmy-13978-profile',
                      'https://uww.org/athletes-results/fergat-abdelkarim-7056-profile',
                      #'https://uww.org/athletes-results/sharshenbekov-zholaman-20714-profile',
                      #'https://uww.org/athletes-results/walihan-sailike-24216-profile',
                      #'https://uww.org/athletes-results/ciobanu-victor-4988-profile',
                      #'https://uww.org/athletes-results/melikyan-armen-14921-profile'
                      ]
    
urls_mgr77kg = ['https://uww.org/athletes-results/makhmudov-akzhol-14057-profile',
                 'https://uww.org/athletes-results/suleymanov-sanan-21913-profile',
                 'https://uww.org/athletes-results/amoyan-malkhas-1562-profile',
                 'https://uww.org/athletes-results/kusaka-nao-12856-profile',
                 'https://uww.org/athletes-results/vardanyan-aram-23785-profile',
                 'https://uww.org/athletes-results/pena-flores-yosvanys-17838-profile',
                 'https://uww.org/athletes-results/cuero-munoz-jair-alexis-5201-profile',
                 'https://uww.org/athletes-results/ouakali-abd-elkrim-17351-profile',
                 'https://uww.org/athletes-results/abdelrahman-mahmoud-khaled-abdelsatar-99-profile',
                 'https://uww.org/athletes-results/akbudak-burhan-701-profile',
                 'https://uww.org/athletes-results/jonni-kunnari-sarkkinen-26242-profile',
                 'https://uww.org/athletes-results/zhadrayev-demeu-25214-profile',
                 'https://uww.org/athletes-results/amin-yavar-kaviyaninejad-11171-profile',
                 'https://uww.org/athletes-results/mnatsakanian-aik-15318-profile',
                 'https://uww.org/athletes-results/sergei-kutuzov-12886-profile',
                 'https://uww.org/athletes-results/levai-zoltan-183618-profile'
                 ]
    
mgr87kg = ['https://uww.org/athletes-results/cengiz-ali-4508-profile',
               'https://uww.org/athletes-results/losonczi-david-13664-profile',
               'https://uww.org/athletes-results/beleniuk-zhan-3232-profile',
               'https://uww.org/athletes-results/novikov-semen-16695-profile',
               'https://uww.org/athletes-results/tursynov-nursultan-45130-profile',
               'https://uww.org/athletes-results/woods-spencer-24421-profile',
               'https://uww.org/athletes-results/munoz-jaramillo-carlos-andres-127436-profile',
               'https://uww.org/athletes-results/sid-azara-bachir-21030-profile',
               'https://uww.org/athletes-results/metwally-mohamed-moustafa-ahmed-abdall-15035-profile',
               'https://uww.org/athletes-results/aleksandr-andreevitch-komarov-25996-profile',
               'https://uww.org/athletes-results/alirzaev-milad-valerikovitch-1196-profile',
               'https://uww.org/athletes-results/qian-haitao-18516-profile',
               'https://uww.org/athletes-results/mohmadipiani-alireza-azizkhoon-71038-profile',
               'https://uww.org/athletes-results/maskevich-kiryl-14626-profile',
               'https://uww.org/athletes-results/huseynov-rafig-9425-profile',
               'https://uww.org/athletes-results/kulynycz-arkadiusz-marcin-12702-profile']
    
mgr97kg = ['https://uww.org/athletes-results/rosillo-kindelan-gabriel-alejandro-19320-profile',
               'https://uww.org/athletes-results/aleksanyan-artur-1068-profile',
               'https://uww.org/athletes-results/omarov-artur-17094-profile',
               'https://uww.org/athletes-results/saravi-mohammadhadi-abdollah-20053-profile',
               'https://uww.org/athletes-results/khaslakhanau-abubakar-70129-profile',
               'https://uww.org/athletes-results/mejia-castillo-kevin-14894-profile',
               'https://uww.org/athletes-results/vera-garcia-alan-ernesto-23927-profile',
               'https://uww.org/athletes-results/rouabah-fadi-19344-profile',
               'https://uww.org/athletes-results/gabr-mohamed-ali-elsayed-7369-profile',
               'https://uww.org/athletes-results/kobliashvili-roberti-12079-profile',
               'https://uww.org/athletes-results/venckaitis-mindaugas-23918-profile',
               'https://uww.org/athletes-results/assakalov-rustam-2118-profile',
               'https://uww.org/athletes-results/kim-seungjun-11880-profile',
               'https://uww.org/athletes-results/savolainen-arvi-martin-20191-profile',
               'https://uww.org/athletes-results/sargsian-artur-20063-profile',
               'https://uww.org/athletes-results/uzur-dzhuzupbekov-25903-profile']
    
mgr130kg = ['https://uww.org/athletes-results/mirzazadeh-amin-mohammadzaman-15237-profile',
                'https://uww.org/athletes-results/kayaalp-riza-11205-profile',
                'https://uww.org/athletes-results/mohamed-abdellatif-mohamed-ahmed-25991-profile',
                'https://uww.org/athletes-results/pino-hinds-oscar-26064-profile',
                'https://uww.org/athletes-results/meng-lingzhe-14971-profile',
                'https://uww.org/athletes-results/schultz-cohlton-26145-profile',
                'https://uww.org/athletes-results/acosta-fernandez-yasmani-401-profile',
                'https://uww.org/athletes-results/guennichi-amine-8354-profile',
                'https://uww.org/athletes-results/assad-oussama-67344-profile',
                'https://uww.org/athletes-results/krahmer-jello-12469-profile',
                'https://uww.org/athletes-results/semenov-sergei-20402-profile',
                'https://uww.org/athletes-results/lee-seungchan-13238-profile',
                'https://uww.org/athletes-results/syzdykov-alimkhan-22098-profile',
                'https://uww.org/athletes-results/alexuc-ciurariu-alin-1092-profile',
                'https://uww.org/athletes-results/shariati-sabah-saleh-20665-profile',
                'https://uww.org/athletes-results/hlinchuk-pavel-9130-profile']
    
    #------------mfs-----------------------------------

mfs57kg = ['https://uww.org/athletes-results/micic-stevan-andria-15077-profile',
               'https://uww.org/athletes-results/higuchi-rei-9100-profile',
               'https://uww.org/athletes-results/harutyunyan-arsen-8820-profile',
               'https://uww.org/athletes-results/abakarov-zelimkhan-26965-profile',
               'https://uww.org/athletes-results/uguev-zavur-26093-profile',
               'https://uww.org/athletes-results/roman-guillermo-bravo-young-142459-profile',
               'https://uww.org/athletes-results/cruz-darian-toi-5172-profile',
               'https://uww.org/athletes-results/mohamed-gamal-abdelnaser-hanafy-15357-profile',
               'https://uww.org/athletes-results/iuna-fafe-diamantino-9936-profile',
               'https://uww.org/athletes-results/rzazade-aliabbas-27696-profile',
               'https://uww.org/athletes-results/tsiutryn-aryan-22770-profile',
               'https://uww.org/athletes-results/almaz-uulu-bekzat-1322-profile',
               'https://uww.org/athletes-results/abdullaev-gulomjon-186-profile',
               'https://uww.org/athletes-results/lee-spencer-richard-165282-profile',
               'https://uww.org/athletes-results/aman-aman-1447-profile',
               'https://uww.org/athletes-results/zou-wanhao-25552-profile']
    
mfs65kg = ['https://uww.org/athletes-results/muszukajev-iszmail-15952-profile',
               'https://uww.org/athletes-results/rivera-sebastian-c-19136-profile',
               'https://uww.org/athletes-results/mamedov-shamil-14213-profile',
               'https://uww.org/athletes-results/tevanyan-vazgen-22649-profile',
               'https://uww.org/athletes-results/amouzadkhalili-rahman-mousa-1561-profile',
               'https://uww.org/athletes-results/gomez-austin-klee-184929-profile',
               'https://uww.org/athletes-results/valdes-tobier-alejandro-enrique-23705-profile',
               'https://uww.org/athletes-results/akazawa-gaku-162898-profile',
               'https://uww.org/athletes-results/okorokov-georgii-36875-profile',
               'https://uww.org/athletes-results/dzebisashvili-goderdzi-166009-profile',
               'https://uww.org/athletes-results/aliyev-haji-1223-profile',
               'https://uww.org/athletes-results/kiyooka-kotaro-185450-profile',
               'https://uww.org/athletes-results/ernazar-akmataliev-25874-profile',
               'https://uww.org/athletes-results/dudaev-islam-6173-profile',
               'https://uww.org/athletes-results/tumur-ochir-tulga-23286-profile',
               'https://uww.org/athletes-results/retherford-zain-allen-19008-profile']
    
mfs74kg = ['https://uww.org/athletes-results/sidakov-zaurbek-21031-profile',
               'https://uww.org/athletes-results/dake-kyle-douglas-5305-profile',
               'https://uww.org/athletes-results/cabolov-hetik-23101-profile',
               'https://uww.org/athletes-results/takatani-daichi-26958-profile',
               'https://uww.org/athletes-results/kougioumtsidis-georgios-12387-profile',
               'https://uww.org/athletes-results/garzon-caballero-geandry-7631-profile',
               'https://uww.org/athletes-results/montero-chirinos-anthony-jose-15509-profile',
               'https://uww.org/athletes-results/ndum-bacar-73894-profile',
               'https://uww.org/athletes-results/amr-hussen-9434-profile',
               'https://uww.org/athletes-results/bayramov-turan-3057-profile',
               'https://uww.org/athletes-results/mahamedkhabib-kadzimahamedau-31428-profile',
               'https://uww.org/athletes-results/abdurakhmonov-bekzod-232-profile',
               'https://uww.org/athletes-results/yones-aliakbar-emamichoghaei-6593-profile',
               'https://uww.org/athletes-results/rassadin-viktor-18878-profile',
               'https://uww.org/athletes-results/salkazanov-tajmuraz-mairbekovic-19848-profile',
               'https://uww.org/athletes-results/chermen-valiev-25867-profile',
               'https://uww.org/athletes-results/mahdavi-iman-184044-profile']
    
mfs86kg = ['https://uww.org/athletes-results/taylor-iii-david-morris-22503-profile',
               'https://uww.org/athletes-results/yazdanicharati-hassan-aliazam-24666-profile',
               'https://uww.org/athletes-results/amine-myles-nazem-1516-profile',
               'https://uww.org/athletes-results/dauletbekov-azamat-5451-profile',
               'https://uww.org/athletes-results/shapiev-javrail-20647-profile',
               'https://uww.org/athletes-results/ramos-ethan-adrian-18792-profile',
               'https://uww.org/athletes-results/moore-alexander-robert-15525-profile',
               'https://uww.org/athletes-results/lawrence-jayden-alexander-13136-profile',
               'https://uww.org/athletes-results/benferdjallah-fateh-3311-profile',
               'https://uww.org/athletes-results/naifonov-artur-16105-profile',
               'https://uww.org/athletes-results/nurmagomedov-osman-51725-profile',
               'https://uww.org/athletes-results/ishiguro-hayato-9820-profile',
               'https://uww.org/athletes-results/bat-erdene-byambasuren-4232-profile',
               'https://uww.org/athletes-results/kurugliev-dauren-12849-profile',
               'https://uww.org/athletes-results/magomed-eldarovitch-ramazanov-26961-profile',
               'https://uww.org/athletes-results/vladimeri-gamkrelidze-7490-profile']
    
mfs97kg = ['https://uww.org/athletes-results/tazhudinov-akhmed-magomed-o-182427-profile',
               'https://uww.org/athletes-results/magomedov-magomedkhan-magomedovitch-13929-profile',
               'https://uww.org/athletes-results/snyder-kyle-frederick-21379-profile',
               'https://uww.org/athletes-results/givi-matcharashvili-132428-profile',
               'https://uww.org/athletes-results/ciftci-ibrahim-4963-profile',
               'https://uww.org/athletes-results/perez-sosa-luis-miguel-17913-profile',
               'https://uww.org/athletes-results/silot-torres-arturo-21084-profile',
               'https://uww.org/athletes-results/elders-mostafa-aly-elsayed-gabr-6526-profile',
               'https://uww.org/athletes-results/de-lange-nicolaas-johannes-steyn-5539-profile',
               'https://uww.org/athletes-results/zhabrailov-alikhan-25212-profile',
               'https://uww.org/athletes-results/hushtyn-aliaksandr-9428-profile',
               'https://uww.org/athletes-results/yergali-alisher-24726-profile',
               'https://uww.org/athletes-results/amirali-hamid-azarpira-2328-profile',
               'https://uww.org/athletes-results/thiele-erik-sven-22672-profile',
               'https://uww.org/athletes-results/baranowski-zbigniew-mateusz-2774-profile',
               'https://uww.org/athletes-results/habila-awusayiman-8589-profile']
    
mfs125kg = ['https://uww.org/athletes-results/zare-amir-hossein-abbas-25126-profile',
                'https://uww.org/athletes-results/petriashvili-geno-26026-profile',
                'https://uww.org/athletes-results/akgul-taha-26079-profile',
                'https://uww.org/athletes-results/parris-mason-mark-17690-profile',
                'https://uww.org/athletes-results/kurbanov-abdulla-69486-profile',
                'https://uww.org/athletes-results/smith-jonovan-darius-159544-profile',
                'https://uww.org/athletes-results/amarveer-dhesi-27485-profile',
                'https://uww.org/athletes-results/ashton-adeyemi-amin-mutuwa-195804-profile',
                'https://uww.org/athletes-results/diaaeldin-kamal-gouda-abdelmottaleb-127616-profile',
                'https://uww.org/athletes-results/dzianis-khramiankou-25870-profile',
                'https://uww.org/athletes-results/giorgi-meshvildishvili-157724-profile',
                'https://uww.org/athletes-results/lkhagvagerel-munkhtur-15797-profile',
                'https://uww.org/athletes-results/batirmurzaev-yusup-2958-profile',
                'https://uww.org/athletes-results/lazarev-aiaal-13140-profile',
                'https://uww.org/athletes-results/deng-zhiwei-5691-profile',
                'https://uww.org/athletes-results/ligeti-daniel-13414-profile']
    
wfs50kg = ['https://uww.org/athletes-results/susaki-yui-21999-profile',
               'https://uww.org/athletes-results/dolgorjav-otgonjargal-5981-profile',
               'https://uww.org/athletes-results/feng-ziqi-7047-profile',
               'https://uww.org/athletes-results/hildebrandt-sarah-ann-9103-profile',
               'https://uww.org/athletes-results/demirhan-yavuz-evin-5672-profile',
               'https://uww.org/athletes-results/cardozo-rey-alisson-camila-4389-profile',
               'https://uww.org/athletes-results/yusneylis-guzman-lopez-8540-profile',
               'https://uww.org/athletes-results/nada-medani-ashour-abdalla-mohamed-15372-profile',
               'https://uww.org/athletes-results/ibtissem-doudou-26118-profile',
               'https://uww.org/athletes-results/livach-oksana-13535-profile',
               'https://uww.org/athletes-results/sokolova-nadezhda-21424-profile',
               'https://uww.org/athletes-results/keunimjaeva-aktenge-11387-profile',
               'https://uww.org/athletes-results/vinesh-vinesh-24032-profile',
               'https://uww.org/athletes-results/kim-son-hyang-11885-profile',
               'https://uww.org/athletes-results/blayvas-anastasia-3618-profile',
               'https://uww.org/athletes-results/stadnik-mariya-21641-profile']
    
wfs53kg = ['https://uww.org/athletes-results/fujinami-akari-7321-profile',
               'https://uww.org/athletes-results/kaladzinskaya-vanesa-10647-profile',
               'https://uww.org/athletes-results/yepez-guzman-lucia-yamileth-24710-profile',
               'https://uww.org/athletes-results/antim-antim-1726-profile',
               'https://uww.org/athletes-results/emma-jonna-denise-malmgren-26793-profile',
               'https://uww.org/athletes-results/parrish-dominique-olivia-17691-profile',
               'https://uww.org/athletes-results/arguello-villegas-betzabeth-angelica-1859-profile',
               'https://uww.org/athletes-results/ogunsanya-christianah-tolulope-16949-profile',
               'https://uww.org/athletes-results/aquino-mia-lahnee-ramos-1788-profile',
               'https://uww.org/athletes-results/ana-andreea-beatrice-1575-profile',
               'https://uww.org/athletes-results/malysheva-natalia-14175-profile',
               'https://uww.org/athletes-results/pang-qianyu-17569-profile',
               'https://uww.org/athletes-results/choe-hyo-gyong-52855-profile',
               'https://uww.org/athletes-results/dragutan-mariana-6114-profile',
               'https://uww.org/athletes-results/khulan-batkhuyag-36279-profile',
               'https://uww.org/athletes-results/yetgil-zeynep-24787-profile']
    
wfs57kg = ['https://uww.org/athletes-results/nichita-anastasia-16489-profile',
               'https://uww.org/athletes-results/sakurai-tsugumi-19786-profile',
               'https://uww.org/athletes-results/adekuoroye-odunayo-folasade-430-profile',
               'https://uww.org/athletes-results/helen-louise-maroulis-27503-profile',
               'https://uww.org/athletes-results/lysak-anhelina-13787-profile',
               'https://uww.org/athletes-results/valverde-melendres-luisa-elizabeth-23743-profile',
               'https://uww.org/athletes-results/taylor-hannah-fay-22501-profile',
               'https://uww.org/athletes-results/aquino-rckaela-maree-ramos-1789-profile',
               'https://uww.org/athletes-results/aouissi-chaimaa-fouzia-1765-profile',
               'https://uww.org/athletes-results/paruszewski-sandra-17701-profile',
               'https://uww.org/athletes-results/kurachkina-iryna-12770-profile',
               'https://uww.org/athletes-results/hong-kexin-188896-profile',
               'https://uww.org/athletes-results/anshu-anshu-26140-profile',
               'https://uww.org/athletes-results/khoroshavtseva-olga-11663-profile',
               'https://uww.org/athletes-results/penalber-giullia-19192-profile',
               'https://uww.org/athletes-results/russo-aurora-19440-profile']
    
wfs62kg = ['https://uww.org/athletes-results/tynybekova-aisuluu-25995-profile',
               'https://uww.org/athletes-results/motoki-sakura-15658-profile',
               'https://uww.org/athletes-results/bullen-grace-jacob-4134-profile',
               'https://uww.org/athletes-results/koliadenko-iryna-12183-profile',
               'https://uww.org/athletes-results/niemesch-luisa-helga-gerda-16514-profile',
               'https://uww.org/athletes-results/godinez-gonzalez-ana-paula-7988-profile',
               'https://uww.org/athletes-results/miracle-kayla-colleen-kiyoko-15192-profile',
               'https://uww.org/athletes-results/kolawole-esther-omolayo-12162-profile',
               'https://uww.org/athletes-results/siwar-bouseta-3890-profile',
               'https://uww.org/athletes-results/dudova-bilyana-zhivkova-6183-profile',
               'https://uww.org/athletes-results/alina-kasabieva-149629-profile',
               'https://uww.org/athletes-results/orkhon-purevdorj-18482-profile',
               'https://uww.org/athletes-results/hyon-gyong-mun-26849-profile',
               'https://uww.org/athletes-results/incze-kriszta-tunde-9717-profile',
               'https://uww.org/athletes-results/nesrin-bas-26250-profile',
               'https://uww.org/athletes-results/veranika-ivanova-10015-profile']
    
wfs68kg = ['https://uww.org/athletes-results/cavusoglu-tosun-buse-22995-profile',
               'https://uww.org/athletes-results/enkhsaikhan-delgermaa-6639-profile',
               'https://uww.org/athletes-results/larroque-koumba-selene-fanta-13093-profile',
               'https://uww.org/athletes-results/ringaci-irina-19113-profile',
               'https://uww.org/athletes-results/ishii-ami-9823-profile',
               'https://uww.org/athletes-results/elor-amit-6560-profile',
               'https://uww.org/athletes-results/caraballo-hernandez-soleymi-antonieta-4373-profile',
               'https://uww.org/athletes-results/oborududu-blessing-16883-profile',
               'https://uww.org/athletes-results/ford-tayla-tuahine-7207-profile',
               'https://uww.org/athletes-results/wiktoria-choluj-101465-profile',
               'https://uww.org/athletes-results/khanum-velieva-23906-profile',
               'https://uww.org/athletes-results/sol-gum-pak-196311-profile',
               'https://uww.org/athletes-results/zhumanazarova-meerim-25435-profile',
               'https://uww.org/athletes-results/nisha-nisha-195329-profile',
               'https://uww.org/athletes-results/zhou-feng-25400-profile',
               'https://uww.org/athletes-results/linda-morais-15556-profile']
    
wfs76kg = ['https://uww.org/athletes-results/medet-kyzy-aiperi-14821-profile',
               'https://uww.org/athletes-results/kagami-yuka-10571-profile',
               'https://uww.org/athletes-results/renteria-renteria-tatiana-18999-profile',
               'https://uww.org/athletes-results/gray-adeline-maria-8224-profile',
               'https://uww.org/athletes-results/marin-potrille-milaimys-de-la-caridad-14462-profile',
               'https://uww.org/athletes-results/justina-renay-di-stasio-25933-profile',
               'https://uww.org/athletes-results/genesis-rosangela-reasco-valdez-18944-profile',
               'https://uww.org/athletes-results/hannah-amuchechi-rueben-26932-profile',
               'https://uww.org/athletes-results/zaineb-sghaier-20531-profile',
               'https://uww.org/athletes-results/nagy-bernadett-16086-profile',
               'https://uww.org/athletes-results/adar-yigit-yasemin-420-profile',
               'https://uww.org/athletes-results/reetika-reetika-18962-profile',
               'https://uww.org/athletes-results/juan-wang-25760-profile',
               'https://uww.org/athletes-results/catalina-axente-2267-profile',
               'https://uww.org/athletes-results/yuliana-vasileva-yaneva-24586-profile',
               'https://uww.org/athletes-results/davaanasan-enkh-amar-6630-profile']
    
