def GetData():
    arr = [('gr', '60 Kg', 'Kenichiro FUMITA', 'Zholaman SHARSHENBEKOV', ('4', '0'), 'Kenichiro FUMITA', 'by VPO', 'Feb 2020'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Islomjon BAKHRAMOV', ('9', '0'), 'Kenichiro FUMITA', 'by VSU', 'Feb 2020'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Gyanender GYANENDER', ('9', '0'), 'Kenichiro FUMITA', 'by VSU', 'Feb 2020'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Sergey EMELIN', ('10', '5'), 'Kenichiro FUMITA', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Ali Reza Ayat Ollah NEJATI', ('10', '1'), 'Kenichiro FUMITA', 'by VSU1', 'Sep 2019'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Victor CIOBANU', ('12', '5'), 'Kenichiro FUMITA', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Elmurat TASMURADOV', ('9', '1'), 'Kenichiro FUMITA', 'by VSU1', 'Sep 2019'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Andres Roberto MONTANO ARROYO', ('3', '1'), 'Kenichiro FUMITA', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Rakhmatsikhudo KHAIBARAU', 'Kenichiro FUMITA', ('0', '0'), 'Rakhmatsikhudo KHAIBARAU', 'by VFO', 'Jul 2019'),
('gr', '60 Kg', 'Seunghak KIM', 'Kenichiro FUMITA', ('0', '0'), 'Seunghak KIM', 'by VFO', 'Jul 2019'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Sailike WALIHAN', ('0', '0'), 'Kenichiro FUMITA', 'by VIN', 'Apr 2019'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Umit DURDYYEV', ('12', '4'), 'Kenichiro FUMITA', 'by VSU1', 'Apr 2019'),
('gr', '60 Kg', 'Se Ung RI', 'Kenichiro FUMITA', ('5', '3'), 'Se Ung RI', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Mehrdad Abdmohammad MARDANI', ('3', '2'), 'Kenichiro FUMITA', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Murad MAMMADOV', ('10', '1'), 'Kenichiro FUMITA', 'by VFA', 'Nov 2018'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Mehdi Seifollah MOHSEN NEJAD', ('7', '0'), 'Kenichiro FUMITA', 'by VPO', 'Nov 2018'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Armen MELIKYAN', ('9', '6'), 'Kenichiro FUMITA', 'by VPO1', 'Nov 2018'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Christopher Josef KRAEMER', ('9', '0'), 'Kenichiro FUMITA', 'by VSU', 'Nov 2018'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Mirambek AINAGULOV', ('2', '1'), 'Kenichiro FUMITA', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Kanybek ZHOLCHUBEKOV', ('2', '1'), 'Kenichiro FUMITA', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Stepan MARYANYAN', ('4', '2'), 'Kenichiro FUMITA', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Vazgen KHACHATRYAN', ('8', '0'), 'Kenichiro FUMITA', 'by VSU', 'Aug 2017'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Justas PETRAVICIUS', ('5', '2'), 'Kenichiro FUMITA', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Mirambek AINAGULOV', ('2', '1'), 'Kenichiro FUMITA', 'by VPO1', 'May 2017'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Saman Morad ABDOUVALI', ('9', '4'), 'Kenichiro FUMITA', 'by VPO1', 'May 2017'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Kaly SULAIMANOV', ('11', '2'), 'Kenichiro FUMITA', 'by VFA', 'May 2017'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Haneul LEE', ('5', '3'), 'Kenichiro FUMITA', 'by VPO1', 'May 2017'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Firuz TUKHTAEV', ('5', '4'), 'Kenichiro FUMITA', 'by VFA', 'Nov 2016'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Kanybek ZHOLCHUBEKOV', ('4', '1'), 'Kenichiro FUMITA', 'by VPO1', 'Nov 2016'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Taleh MAMMADOV', ('10', '0'), 'Kenichiro FUMITA', 'by VSU', 'Nov 2016'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Murad MAMMADOV', ('7', '4'), 'Kenichiro FUMITA', 'by VPO1', 'Nov 2016'),
('gr', '60 Kg', 'Mehrad MARDANI', 'Kenichiro FUMITA', ('0', '0'), 'Mehrad MARDANI', 'by VIN', 'Nov 2015'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Kenichiro FUMITA', ('10', '5'), 'Elmurat TASMURADOV', 'by VFA', 'Nov 2015'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Arsen ERALIEV', ('9', '7'), 'Kenichiro FUMITA', 'by VPO1', 'Nov 2015'),
('gr', '60 Kg', 'Sergey EMELIN', 'Kenichiro FUMITA', ('9', '7'), 'Sergey EMELIN', 'by VPO1', 'Aug 2014'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Muradi MIKELADZE', ('4', '1'), 'Kenichiro FUMITA', 'by VPO', 'Aug 2014'),
('gr', '60 Kg', 'Sergey EMELIN', 'Kerem KAMAL', ('4', '1'), 'Sergey EMELIN', 'by VPO1', 'Apr 2021'),
('gr', '60 Kg', 'Sergey EMELIN', 'Razvan ARNAUT', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Apr 2021'),
('gr', '60 Kg', 'Sergey EMELIN', 'Jozsef ANDRASI', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Apr 2021'),
('gr', '60 Kg', 'Sergey EMELIN', 'Grzegorz KUNKEL', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Apr 2021'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Sergey EMELIN', ('10', '5'), 'Kenichiro FUMITA', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Mirambek AINAGULOV', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Sep 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Lenur TEMIROV', ('10', '0'), 'Sergey EMELIN', 'by VSU', 'Sep 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Razvan ARNAUT', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Sep 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Erik TORBA', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Sep 2019'),
('gr', '60 Kg', 'Victor CIOBANU', 'Sergey EMELIN', ('5', '5'), 'Victor CIOBANU', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Kerem KAMAL', ('7', '0'), 'Sergey EMELIN', 'by VPO', 'Apr 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Helary MAEGISALU', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Apr 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Virgil MUNTEANU', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Apr 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Sailike WALIHAN', ('7', '2'), 'Sergey EMELIN', 'by VPO1', 'Feb 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Mustafa SAGLAM', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Feb 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Rustam TEIISHOV', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Feb 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Elcin ALI', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Feb 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Victor CIOBANU', ('10', '1'), 'Sergey EMELIN', 'by VSU1', 'Oct 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Aidos SULTANGALI', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Oct 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Se Ung RI', ('7', '0'), 'Sergey EMELIN', 'by VPO', 'Oct 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Oct 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Maksim KAZHARSKI', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Oct 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Lauri MAHONEN', ('12', '4'), 'Sergey EMELIN', 'by VSU1', 'Sep 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Tony BRALA', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Sep 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Mingiyan SEMENOV', ('3', '1'), 'Sergey EMELIN', 'by VPO1', 'Sep 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Jozsef ANDRASI', ('11', '1'), 'Sergey EMELIN', 'by VSU1', 'Sep 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Murad MAMMADOV', ('6', '5'), 'Sergey EMELIN', 'by VPO1', 'Apr 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Dato CHKHARTISHVILI', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Apr 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Erik TORBA', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Apr 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Etienne KINSINGER', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Apr 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Mingiyan SEMENOV', ('2', '2'), 'Sergey EMELIN', 'by VPO1', 'Jan 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Artur PETROSIAN', ('3', '0'), 'Sergey EMELIN', 'by VPO', 'Jan 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Ruben MINASIAN', ('5', '2'), 'Sergey EMELIN', 'by VPO1', 'Jan 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Rodion SAMATOV', ('5', '4'), 'Sergey EMELIN', 'by VPO1', 'Jan 2018'),
('gr', '60 Kg', 'Masuto KAWANA', 'Sergey EMELIN', ('15', '14'), 'Masuto KAWANA', 'by VPO1', 'Nov 2017'),
('gr', '60 Kg', 'Sergey EMELIN', 'Sakit GULIYEV', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Nov 2017'),
('gr', '60 Kg', 'Sergey EMELIN', 'Taron DUMOYAN', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Nov 2017'),
('gr', '60 Kg', 'Sergey EMELIN', 'Przemyslaw PIATEK', ('9', '1'), 'Sergey EMELIN', 'by VSU1', 'Nov 2017'),
('gr', '60 Kg', 'Sergey EMELIN', 'Abdulmazhit BAKIZHONOV', ('3', '1'), 'Sergey EMELIN', 'by VPO1', 'Jan 2017'),
('gr', '60 Kg', 'Mingiyan SEMENOV', 'Sergey EMELIN', ('6', '0'), 'Mingiyan SEMENOV', 'by VPO', 'Jan 2017'),
('gr', '60 Kg', 'Sergey EMELIN', 'Saddyk LALAEV', ('4', '1'), 'Sergey EMELIN', 'by VPO1', 'Jan 2017'),
('gr', '60 Kg', 'Sergey EMELIN', 'Firuz TUKHTAEV', ('2', '1'), 'Sergey EMELIN', 'by VPO1', 'Jan 2017'),
('gr', '60 Kg', 'Sergey EMELIN', 'Roman IVANOV', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Jan 2017'),
('gr', '60 Kg', 'Abdol Mohammad PAPI', 'Sergey EMELIN', ('12', '4'), 'Abdol Mohammad PAPI', 'by VSU1', 'Dec 2016'),
('gr', '60 Kg', 'Sergey EMELIN', 'Elmar TALANT BEKUULU', ('10', '1'), 'Sergey EMELIN', 'by VSU1', 'Dec 2016'),
('gr', '60 Kg', 'Sergey EMELIN', 'Przemyslaw PIATEK', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Dec 2016'),
('gr', '60 Kg', 'Saman Morad ABDOULI', 'Sergey EMELIN', ('2', '1'), 'Saman Morad ABDOULI', 'by VPO1', 'May 2016'),
('gr', '60 Kg', 'Sergey EMELIN', 'Mirambek AINAGULOV', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'May 2016'),
('gr', '60 Kg', 'Sergey EMELIN', 'Elbek TAZHYIEU', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'May 2016'),
('gr', '60 Kg', 'Sergey EMELIN', 'Murad MAMMADOV', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Mar 2016'),
('gr', '60 Kg', 'Sergey EMELIN', 'Etienne KINSINGER', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Mar 2016'),
('gr', '60 Kg', 'Sergey EMELIN', 'Tamas NAD', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Mar 2016'),
('gr', '60 Kg', 'Sergey EMELIN', 'Khvicha TCHITAVA', ('10', '1'), 'Sergey EMELIN', 'by VSU1', 'Mar 2016'),
('gr', '60 Kg', 'Sergey EMELIN', 'Mihai Radu MIHUT', ('10', '8'), 'Sergey EMELIN', 'by VPO1', 'Aug 2014'),
('gr', '60 Kg', 'Sergey EMELIN', 'Kristijan SIMATIC', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Aug 2014'),
('gr', '60 Kg', 'Karen ASLAYAN', 'Sergey EMELIN', ('29', '0'), 'Karen ASLAYAN', 'by VSU', 'Aug 2014'),
('gr', '60 Kg', 'Sergey EMELIN', 'Kenichiro FUMITA', ('9', '7'), 'Sergey EMELIN', 'by VPO1', 'Aug 2014'),
('gr', '60 Kg', 'Sergey EMELIN', 'Dante RODRIGUEZ', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Aug 2014'),
('gr', '60 Kg', 'Marat Maksumovitch GARIPOV', 'Mirambek AINAGULOV', ('11', '7'), 'Marat Maksumovitch GARIPOV', 'by VPO1', 'Mar 2021'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Lenur TEMIROV', ('10', '0'), 'Mirambek AINAGULOV', 'by VSU', 'Sep 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Mirambek AINAGULOV', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Sep 2019'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Ivan LIZATOVIC', ('10', '0'), 'Mirambek AINAGULOV', 'by VSU', 'Sep 2019'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Justas PETRAVICIUS', ('4', '2'), 'Mirambek AINAGULOV', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Marat GARIPOV', ('9', '0'), 'Mirambek AINAGULOV', 'by VSU', 'Sep 2019'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Roman Aleksandrovich IVANOV', ('9', '0'), 'Mirambek AINAGULOV', 'by VSU', 'Jul 2019'),
('gr', '60 Kg', 'Shinobu OTA', 'Mirambek AINAGULOV', ('9', '8'), 'Shinobu OTA', 'by VPO1', 'Jul 2019'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Damir ZARLYKHANOV', ('3', '1'), 'Mirambek AINAGULOV', 'by VPO1', 'Jul 2019'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Shamil Salauddinovitch MUALIEV', ('6', '3'), 'Mirambek AINAGULOV', 'by VPO1', 'Jul 2019'),
('gr', '60 Kg', 'Jungbaik LEE', 'Mirambek AINAGULOV', ('6', '4'), 'Jungbaik LEE', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Se Ung RI', ('13', '5'), 'Mirambek AINAGULOV', 'by VSU1', 'Aug 2018'),
('gr', '60 Kg', 'Kanybek ZHOLCHUBEKOV', 'Mirambek AINAGULOV', ('9', '0'), 'Kanybek ZHOLCHUBEKOV', 'by VSU', 'Aug 2018'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'DANG TIEN DOI', ('9', '0'), 'Mirambek AINAGULOV', 'by VSU', 'Aug 2018'),
('gr', '60 Kg', 'Krisztian Istvan VANCZA', 'Mirambek AINAGULOV', ('5', '5'), 'Krisztian Istvan VANCZA', 'by VPO1', 'Jun 2018'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Mihai Radu MIHUT', ('6', '4'), 'Mirambek AINAGULOV', 'by VPO1', 'Jun 2018'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Vikram Krushnath KURADE', ('9', '0'), 'Mirambek AINAGULOV', 'by VSU', 'Feb 2018'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Mirambek AINAGULOV', ('12', '0'), 'Elmurat TASMURADOV', 'by VPO1', 'Feb 2018'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Keramat Morad ABDEVALI', ('10', '0'), 'Mirambek AINAGULOV', 'by VSU', 'Feb 2018'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Sakit GULIYEV', ('10', '0'), 'Mirambek AINAGULOV', 'by VSU', 'Jan 2018'),
('gr', '60 Kg', 'Mehrdad Abdmohammad MARDANI', 'Mirambek AINAGULOV', ('4', '0'), 'Mehrdad Abdmohammad MARDANI', 'by VPO', 'Jan 2018'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Shirzad Ali BEHESHTITALA', ('3', '1'), 'Mirambek AINAGULOV', 'by VPO1', 'Jan 2018'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Jacopo SANDRON', ('4', '0'), 'Mirambek AINAGULOV', 'by VPO', 'Jan 2018'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Mirambek AINAGULOV', ('2', '1'), 'Kenichiro FUMITA', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Seunghak KIM', ('4', '2'), 'Mirambek AINAGULOV', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Dmytro TSYMBALIUK', ('7', '5'), 'Mirambek AINAGULOV', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Gyanender GYANENDER', ('9', '0'), 'Mirambek AINAGULOV', 'by VSU', 'Aug 2017'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Mostafa Hassan Abdelaal MOHAMED', ('4', '1'), 'Mirambek AINAGULOV', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Mirambek AINAGULOV', ('2', '1'), 'Kenichiro FUMITA', 'by VPO1', 'May 2017'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Li JIANG', ('9', '0'), 'Mirambek AINAGULOV', 'by VSU', 'May 2017'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Sin Myong RI', ('9', '0'), 'Mirambek AINAGULOV', 'by VSU', 'May 2017'),
('gr', '60 Kg', 'Taleh MAMMADOV', 'Mirambek AINAGULOV', ('3', '0'), 'Taleh MAMMADOV', 'by VPO', 'Nov 2016'),
('gr', '60 Kg', 'Fatih Orhan UCUNCU', 'Mirambek AINAGULOV', ('3', '0'), 'Fatih Orhan UCUNCU', 'by VPO', 'May 2016'),
('gr', '60 Kg', 'Sergey EMELIN', 'Mirambek AINAGULOV', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'May 2016'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Elbek TAZHYIEU', ('9', '0'), 'Mirambek AINAGULOV', 'by VSU', 'May 2016'),
('gr', '60 Kg', 'Ravaughn Richard Ravelle PERKINS', 'Mirambek AINAGULOV', ('8', '0'), 'Ravaughn Richard Ravelle PERKINS', 'by VSU', 'Apr 2016'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Ravinder RAVINDER', ('10', '1'), 'Mirambek AINAGULOV', 'by VSU1', 'Apr 2016'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Ritisak PRAVAN', ('8', '0'), 'Mirambek AINAGULOV', 'by VFA', 'Feb 2016'),
('gr', '60 Kg', 'Saman Morad ABDOULI', 'Mirambek AINAGULOV', ('10', '6'), 'Saman Morad ABDOULI', 'by VPO1', 'Feb 2016'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Seydylla TAZAYEV', ('8', '0'), 'Mirambek AINAGULOV', 'by VSU', 'Feb 2016'),
('gr', '60 Kg', 'Arsen ERALIEV', 'Mirambek AINAGULOV', ('2', '1'), 'Arsen ERALIEV', 'by VPO1', 'May 2015'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Mohsen Hossein HAJI POUR', ('7', '2'), 'Mirambek AINAGULOV', 'by VPO1', 'May 2015'),
('gr', '60 Kg', 'Behrooz MALEKI', 'Mirambek AINAGULOV', ('2', '0'), 'Behrooz MALEKI', 'by VFA', 'Aug 2014'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Daniel KOCAR', ('9', '0'), 'Mirambek AINAGULOV', 'by VSU', 'Aug 2014'),
('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Elmurat TASMURADOV', ('7', '5'), 'Ali Reza Ayat Ollah NEJATI', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Ali Reza Ayat Ollah NEJATI', ('10', '1'), 'Kenichiro FUMITA', 'by VSU1', 'Sep 2019'),
('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Ivo Serafimov ANGELOV', ('3', '1'), 'Ali Reza Ayat Ollah NEJATI', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Seunghak KIM', ('7', '0'), 'Ali Reza Ayat Ollah NEJATI', 'by VPO', 'Sep 2019'),
('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('3', '1'), 'Ali Reza Ayat Ollah NEJATI', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Seydylla TAZAYEV', ('9', '0'), 'Ali Reza Ayat Ollah NEJATI', 'by VSU', 'Sep 2019'),
('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Ihor KUROCHKIN', ('9', '0'), 'Ali Reza Ayat Ollah NEJATI', 'by VSU', 'Sep 2018'),
('gr', '60 Kg', 'Vijay VIJAY', 'Ali Reza Ayat Ollah NEJATI', ('4', '4'), 'Vijay VIJAY', 'by VFA', 'Sep 2018'),
('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Andrej GINC', ('9', '0'), 'Ali Reza Ayat Ollah NEJATI', 'by VSU', 'Sep 2018'),
('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Ivo Krasimirov ILIEV', ('10', '0'), 'Ali Reza Ayat Ollah NEJATI', 'by VFA', 'Sep 2018'),
('gr', '60 Kg', 'Galym KABDUNASSAROV', 'Ali Reza Ayat Ollah NEJATI', ('10', '2'), 'Galym KABDUNASSAROV', 'by VSU1', 'Jul 2018'),
('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Turabek TIRKASHEV', ('7', '7'), 'Ali Reza Ayat Ollah NEJATI', 'by VPO1', 'Jul 2018'),
('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Talastan KANZHARBEK UULU', ('9', '0'), 'Ali Reza Ayat Ollah NEJATI', 'by VSU', 'Jul 2018'),
('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Islomidin MAZITOV', ('0', '0'), 'Ali Reza Ayat Ollah NEJATI', 'by VFO', 'Jul 2018'),
('gr', '60 Kg', 'Lenur TEMIROV', 'Stig Andre BERGE', ('3', '3'), 'Lenur TEMIROV', 'by VPO1', 'Feb 2020'),
('gr', '60 Kg', 'Lenur TEMIROV', 'Dawid KARECINSKI', ('5', '1'), 'Lenur TEMIROV', 'by VPO1', 'Feb 2020'),
('gr', '60 Kg', 'Maksim NEHODA', 'Lenur TEMIROV', ('10', '0'), 'Maksim NEHODA', 'by VSU', 'Feb 2020'),
('gr', '60 Kg', 'Mirambek AINAGULOV', 'Lenur TEMIROV', ('10', '0'), 'Mirambek AINAGULOV', 'by VSU', 'Sep 2019'),
('gr', '60 Kg', 'Lenur TEMIROV', 'Razvan ARNAUT', ('3', '2'), 'Lenur TEMIROV', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Lenur TEMIROV', ('10', '0'), 'Sergey EMELIN', 'by VSU', 'Sep 2019'),
('gr', '60 Kg', 'Lenur TEMIROV', 'Ildar HAFIZOV', ('8', '2'), 'Lenur TEMIROV', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Lenur TEMIROV', 'Abdennour LAOUNI', ('4', '3'), 'Lenur TEMIROV', 'by VFA', 'Sep 2019'),
('gr', '60 Kg', 'Lenur TEMIROV', 'Ivan LIZATOVIC', ('9', '0'), 'Lenur TEMIROV', 'by VSU', 'Apr 2019'),
('gr', '60 Kg', 'Victor CIOBANU', 'Lenur TEMIROV', ('6', '4'), 'Victor CIOBANU', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Lenur TEMIROV', 'Murad MAMMADOV', ('10', '5'), 'Lenur TEMIROV', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Lenur TEMIROV', 'Gevorg GHARIBYAN', ('6', '5'), 'Lenur TEMIROV', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Lenur TEMIROV', 'Erbatu TUO', ('3', '1'), 'Lenur TEMIROV', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Lenur TEMIROV', ('4', '3'), 'Elmurat TASMURADOV', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Lenur TEMIROV', 'Urmatbek AMATOV', ('8', '5'), 'Lenur TEMIROV', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Lenur TEMIROV', 'Nikolay Ivanov VICHEV', ('9', '1'), 'Lenur TEMIROV', 'by VFA', 'Oct 2018'),
('gr', '60 Kg', 'Lenur TEMIROV', 'Aidyn NUGUMANOV', ('11', '1'), 'Lenur TEMIROV', 'by VSU1', 'Oct 2018'),
('gr', '60 Kg', 'Lasha MARIAMIDZE', 'Lenur TEMIROV', ('2', '1'), 'Lasha MARIAMIDZE', 'by VPO1', 'Jul 2018'),
('gr', '60 Kg', 'Rahman BILICI', 'Lenur TEMIROV', ('7', '1'), 'Rahman BILICI', 'by VIN', 'Jul 2018'),
('gr', '60 Kg', 'Lenur TEMIROV', 'Alexandru BICIU', ('4', '2'), 'Lenur TEMIROV', 'by VPO1', 'Jul 2018'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Makhmud BAKHSHILLOEV', ('0', '0'), 'Elmurat TASMURADOV', 'by VIN', 'Jun 2021'),
('gr', '60 Kg', 'Murat FIRAT', 'Elmurat TASMURADOV', ('3', '1'), 'Murat FIRAT', 'by VPO1', 'Jun 2021'),
('gr', '60 Kg', 'Urmatbek AMATOV', 'Elmurat TASMURADOV', ('0', '0'), 'Urmatbek AMATOV', 'by VIN', 'Apr 2021'),
('gr', '60 Kg', 'Meysam Karamali DALKHANI', 'Elmurat TASMURADOV', ('9', '7'), 'Meysam Karamali DALKHANI', 'by VPO1', 'Apr 2021'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Mohammed Abbas Shyaa AL SAEDI', ('0', '0'), 'Elmurat TASMURADOV', 'by VFO', 'Apr 2021'),
('gr', '60 Kg', 'Michael PORTMANN', 'Elmurat TASMURADOV', ('0', '0'), 'Michael PORTMANN', 'by VIN', 'Jan 2021'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Jinseub SONG', ('9', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Feb 2020'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Meysam Karamali DALKHANI', ('10', '1'), 'Elmurat TASMURADOV', 'by VSU1', 'Feb 2020'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Sachin RANA', ('8', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Feb 2020'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Yernur FIDAKHMETOV', ('7', '0'), 'Elmurat TASMURADOV', 'by VPO', 'Feb 2020'),
('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Elmurat TASMURADOV', ('7', '5'), 'Ali Reza Ayat Ollah NEJATI', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Victor CIOBANU', ('9', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Sep 2019'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Andres Roberto MONTANO ARROYO', ('0', '0'), 'Elmurat TASMURADOV', 'by VIN', 'Sep 2019'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Elmurat TASMURADOV', ('9', '1'), 'Kenichiro FUMITA', 'by VSU1', 'Sep 2019'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Gevorg GHARIBYAN', ('7', '0'), 'Elmurat TASMURADOV', 'by VPO', 'Sep 2019'),
('gr', '60 Kg', 'Abouhalima Mohamed Elsaid ABOUHALIMA', 'Elmurat TASMURADOV', ('9', '2'), 'Abouhalima Mohamed Elsaid ABOUHALIMA', 'by VPO1', 'Jul 2019'),
('gr', '60 Kg', 'Erbatu TUO', 'Elmurat TASMURADOV', ('4', '3'), 'Erbatu TUO', 'by VIN', 'Apr 2019'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Jinwoong JUNG', ('12', '2'), 'Elmurat TASMURADOV', 'by VSU1', 'Apr 2019'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Urmatbek AMATOV', ('9', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Apr 2019'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Mihai Radu MIHUT', ('4', '1'), 'Elmurat TASMURADOV', 'by VPO1', 'Feb 2019'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Enes BASAR', ('13', '4'), 'Elmurat TASMURADOV', 'by VSU1', 'Feb 2019'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Morten THORESEN', ('2', '1'), 'Elmurat TASMURADOV', 'by VPO1', 'Feb 2019'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Dohyeong KIM', ('11', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Feb 2019'),
('gr', '60 Kg', 'Stepan MARYANYAN', 'Elmurat TASMURADOV', ('6', '3'), 'Stepan MARYANYAN', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Lenur TEMIROV', ('4', '3'), 'Elmurat TASMURADOV', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Donior ISLAMOV', ('9', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Oct 2018'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Erbatu TUO', ('7', '3'), 'Elmurat TASMURADOV', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Soslan DAUROV', ('2', '2'), 'Elmurat TASMURADOV', 'by VFA', 'Oct 2018'),
('gr', '60 Kg', 'Mohammadreza Abdolhamid GERAEI', 'Elmurat TASMURADOV', ('9', '8'), 'Mohammadreza Abdolhamid GERAEI', 'by VFA', 'Aug 2018'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Seydylla TAZAYEV', ('9', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Aug 2018'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Urmatbek AMATOV', ('8', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Feb 2018'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Mirambek AINAGULOV', ('12', '0'), 'Elmurat TASMURADOV', 'by VPO1', 'Feb 2018'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Vikram Krushnath KURADE', ('8', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Feb 2018'),
('gr', '60 Kg', 'Artem SURKOV', 'Elmurat TASMURADOV', ('9', '4'), 'Artem SURKOV', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Matthias MAASCH', ('2', '1'), 'Elmurat TASMURADOV', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Ali Feizollah ARSALAN', 'Elmurat TASMURADOV', ('11', '1'), 'Ali Feizollah ARSALAN', 'by VFA', 'May 2017'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Ying Hua HUNG', ('6', '0'), 'Elmurat TASMURADOV', 'by VFA', 'May 2017'),
('gr', '60 Kg', 'Sanghun OH', 'Elmurat TASMURADOV', ('4', '3'), 'Sanghun OH', 'by VPO1', 'May 2017'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Nurbek ABDUGANIEV', ('2', '1'), 'Elmurat TASMURADOV', 'by VPO1', 'May 2017'),
('gr', '60 Kg', 'Rovshan TAGHIYEV', 'Elmurat TASMURADOV', ('6', '0'), 'Rovshan TAGHIYEV', 'by VPO', 'Nov 2016'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Arsen ERALIEV', ('13', '8'), 'Elmurat TASMURADOV', 'by VPO1', 'Aug 2016'),
('gr', '60 Kg', 'Ismael BORRERO MOLINA', 'Elmurat TASMURADOV', ('4', '1'), 'Ismael BORRERO MOLINA', 'by VPO1', 'Aug 2016'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Won Chol YUN', ('9', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Aug 2016'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Kristian FRIS', ('7', '2'), 'Elmurat TASMURADOV', 'by VPO1', 'Aug 2016'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Revaz LASHKHI', ('4', '0'), 'Elmurat TASMURADOV', 'by VPO', 'Apr 2016'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Ivo Serafimov ANGELOV', ('8', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Apr 2016'),
('gr', '60 Kg', 'Seunghak KIM', 'Elmurat TASMURADOV', ('11', '2'), 'Seunghak KIM', 'by VSU1', 'Apr 2016'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Peter MODOS', ('11', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Apr 2016'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Frunze HARUTYUNYAN', ('11', '2'), 'Elmurat TASMURADOV', 'by VSU1', 'Apr 2016'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Andrey TSARYUK', ('10', '2'), 'Elmurat TASMURADOV', 'by VSU1', 'Apr 2016'),
('gr', '60 Kg', 'Almat KEBISPAYEV', 'Elmurat TASMURADOV', ('9', '0'), 'Almat KEBISPAYEV', 'by VSU', 'Nov 2015'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Jesse THIELKIE', ('14', '4'), 'Elmurat TASMURADOV', 'by VSU1', 'Nov 2015'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Kenichiro FUMITA', ('10', '5'), 'Elmurat TASMURADOV', 'by VFA', 'Nov 2015'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Mehrad MARDANI', ('8', '4'), 'Elmurat TASMURADOV', 'by VPO1', 'Nov 2015'),
('gr', '60 Kg', 'Ivo Serafimov ANGELOV', 'Elmurat TASMURADOV', ('6', '6'), 'Ivo Serafimov ANGELOV', 'by VPO1', 'Sep 2015'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Roman AMOYAN', ('8', '2'), 'Elmurat TASMURADOV', 'by VPO1', 'Sep 2015'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Ali SOTO MACIAS', ('9', '2'), 'Elmurat TASMURADOV', 'by VPO1', 'Sep 2015'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Won Chol YUH', ('9', '4'), 'Elmurat TASMURADOV', 'by VPO1', 'May 2015'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Shinobu OTA', ('9', '0'), 'Elmurat TASMURADOV', 'by VSU', 'May 2015'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Qiye TIAN', ('8', '0'), 'Elmurat TASMURADOV', 'by VSU', 'May 2015'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Ismael BORRERO MOLINA', ('10', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Sep 2014'),
('gr', '60 Kg', 'Hamid Mohammad SORYAN REIHANPOUR', 'Elmurat TASMURADOV', ('2', '1'), 'Hamid Mohammad SORYAN REIHANPOUR', 'by VPO1', 'Sep 2014'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Lumin WANG', ('11', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Sep 2014'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Tonimir SOKOL', ('9', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Sep 2014'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Edward BERSEGIAN', ('8', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Sep 2014'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Ildar HAFIZOV', ('7', '0'), 'Luis Alberto ORTA SANCHEZ', 'by VPO', 'Mar 2020'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Gustavo Jesus RODRIGUEZ MARTINEZ', ('5', '2'), 'Luis Alberto ORTA SANCHEZ', 'by VPO1', 'Mar 2020'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Dicther Hans TORO CASTANEDA', ('4', '3'), 'Luis Alberto ORTA SANCHEZ', 'by VPO1', 'Mar 2020'),
('gr', '60 Kg', 'Jose Javier RODRIGUEZ COLON', 'Luis Alberto ORTA SANCHEZ', ('0', '0'), 'Jose Javier RODRIGUEZ COLON', 'by VIN', 'Mar 2020'),
('gr', '60 Kg', 'John Michael DIAKOMIHALIS', 'Luis Alberto ORTA SANCHEZ', ('0', '0'), 'John Michael DIAKOMIHALIS', 'by VIN', 'Mar 2020'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Anthony Javier PALENCIA PUENTES', ('8', '0'), 'Luis Alberto ORTA SANCHEZ', 'by VSU', 'Aug 2019'),('gr', '60 Kg', 'Andres Roberto MONTANO ARROYO', 'Luis Alberto ORTA SANCHEZ', ('6', '6'), 'Andres Roberto MONTANO ARROYO', 'by VPO1', 'Aug 2019'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Samuel GURRIA VIGUERAS', ('9', '0'), 'Luis Alberto ORTA SANCHEZ', 'by VSU', 'Apr 2019'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Anthony Javier PALENCIA PUENTES', ('7', '4'), 'Luis Alberto ORTA SANCHEZ', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Dalton James ROBERTS', ('8', '0'), 'Luis Alberto ORTA SANCHEZ', 'by VSU', 'Apr 2019'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Andres Orlando GONZALEZ ANDRADE', ('0', '0'), 'Luis Alberto ORTA SANCHEZ', 'by VFO', 'Apr 2019'),('gr', '60 Kg', 'Kristian FRIS', 'Luis Alberto ORTA SANCHEZ', ('7', '1'), 'Kristian FRIS', 'by VFA', 'Oct 2018'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Firuz TUKHTAEV', ('8', '4'), 'Luis Alberto ORTA SANCHEZ', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Jancel Miguel PIMENTEL GONZALEZ', ('0', '0'), 'Luis Alberto ORTA SANCHEZ', 'by VIN', 'May 2018'),('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Dicther Hans TORO CASTANEDA', ('7', '5'), 'Luis Alberto ORTA SANCHEZ', 'by VPO1', 'May 2018'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Andres Roberto MONTANO ARROYO', ('5', '3'), 'Luis Alberto ORTA SANCHEZ', 'by VPO1', 'May 2018'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Javier DUMENIGO GONZALEZ', ('2', '2'), 'Luis Alberto ORTA SANCHEZ', 'by VPO1', 'Feb 2018'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Andrej GINC', ('4', '0'), 'Luis Alberto ORTA SANCHEZ', 'by VPO', 'Feb 2018'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Abbos RAKHMONOV', ('8', '0'), 'Luis Alberto ORTA SANCHEZ', 'by VSU', 'Feb 2018'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Gorge Nickford GONZALES BATIS', ('9', '0'), 'Luis Alberto ORTA SANCHEZ', 'by VSU', 'Feb 2018'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Dalton James ROBERTS', ('8', '0'), 'Luis Alberto ORTA SANCHEZ', 'by VSU', 'Feb 2018'),
('gr', '60 Kg', 'Meysam Karamali DALKHANI', 'Luis Alberto ORTA SANCHEZ', ('3', '1'), 'Meysam Karamali DALKHANI', 'by VPO1', 'Nov 2017'),
('gr', '60 Kg', 'Dicther Hans TORO CASTANEDA', 'Ildar HAFIZOV', ('7', '3'), 'Dicther Hans TORO CASTANEDA', 'by VPO1', 'May 2021'),
('gr', '60 Kg', 'Ildar HAFIZOV', 'Marat GARIPOV', ('10', '1'), 'Ildar HAFIZOV', 'by VSU1', 'May 2021'),
('gr', '60 Kg', 'Ildar HAFIZOV', 'Joshua Xavier MEDINA', ('9', '0'), 'Ildar HAFIZOV', 'by VSU', 'May 2021'),
('gr', '60 Kg', 'Zhanserik SARSENBIYEV', 'Ildar HAFIZOV', ('8', '5'), 'Zhanserik SARSENBIYEV', 'by VPO1', 'Mar 2021'),
('gr', '60 Kg', 'Emin Narimanovitch SEFERSHAEV', 'Ildar HAFIZOV', ('4', '1'), 'Emin Narimanovitch SEFERSHAEV', 'by VPO1', 'Mar 2021'),
('gr', '60 Kg', 'Ildar HAFIZOV', 'Manish MANISH', ('11', '3'), 'Ildar HAFIZOV', 'by VSU1', 'Mar 2021'),
('gr', '60 Kg', 'Luis Alberto ORTA SANCHEZ', 'Ildar HAFIZOV', ('7', '0'), 'Luis Alberto ORTA SANCHEZ', 'by VPO', 'Mar 2020'),
('gr', '60 Kg', 'Ildar HAFIZOV', 'Samuel GURRIA VIGUERAS', ('7', '2'), 'Ildar HAFIZOV', 'by VPO1', 'Mar 2020'),
('gr', '60 Kg', 'Ildar HAFIZOV', 'Marat GARIPOV', ('9', '0'), 'Ildar HAFIZOV', 'by VSU', 'Mar 2020'),
('gr', '60 Kg', 'Ildar HAFIZOV', 'Andres Roberto MONTANO ARROYO', ('4', '3'), 'Ildar HAFIZOV', 'by VPO1', 'Mar 2020'),
('gr', '60 Kg', 'Erbatu TUO', 'Ildar HAFIZOV', ('6', '3'), 'Erbatu TUO', 'by VPO1', 'Jan 2020'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Ildar HAFIZOV', ('9', '1'), 'Sailike WALIHAN', 'by VSU1', 'Jan 2020'),
('gr', '60 Kg', 'Lenur TEMIROV', 'Ildar HAFIZOV', ('8', '2'), 'Lenur TEMIROV', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Ildar HAFIZOV', 'Etienne KINSINGER', ('6', '1'), 'Ildar HAFIZOV', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Ildar HAFIZOV', 'Emilio PEREZ ALFONZO', ('7', '2'), 'Ildar HAFIZOV', 'by VPO1', 'Aug 2019'),
('gr', '60 Kg', 'Dicther Hans TORO CASTANEDA', 'Ildar HAFIZOV', ('8', '3'), 'Dicther Hans TORO CASTANEDA', 'by VPO1', 'Aug 2019'),
('gr', '60 Kg', 'Ivan LIZATOVIC', 'Ildar HAFIZOV', ('2', '1'), 'Ivan LIZATOVIC', 'by VPO1', 'Feb 2019'),
('gr', '60 Kg', 'Ildar HAFIZOV', 'Jozsef ANDRASI', ('10', '0'), 'Ildar HAFIZOV', 'by VSU', 'Feb 2019'),
('gr', '60 Kg', 'Vazgen KHACHATRYAN', 'Ildar HAFIZOV', ('8', '3'), 'Vazgen KHACHATRYAN', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Steven Masao TAKAHASHI', 'Ildar HAFIZOV', ('14', '13'), 'Steven Masao TAKAHASHI', 'by VPO1', 'Mar 2016'),
('gr', '60 Kg', 'Ildar HAFIZOV', 'Ali SOTO MACIAS', ('9', '2'), 'Ildar HAFIZOV', 'by VPO1', 'Mar 2016'),
('gr', '60 Kg', 'Ryan MANGO', 'Ildar HAFIZOV', ('0', '0'), 'Ryan MANGO', 'by VFO', 'Feb 2016'),
('gr', '60 Kg', 'Shinobu OTA', 'Ildar HAFIZOV', ('2', '2'), 'Shinobu OTA', 'by VFA', 'Feb 2016'),
('gr', '60 Kg', 'Ildar HAFIZOV', 'Mate KRASZNAI', ('9', '0'), 'Ildar HAFIZOV', 'by VSU', 'Feb 2016'),
('gr', '60 Kg', 'Ildar HAFIZOV', 'Erik TORBA', ('9', '0'), 'Ildar HAFIZOV', 'by VSU', 'Feb 2016'),
('gr', '60 Kg', 'Ildar HAFIZOV', 'Qiye TIAN', ('8', '0'), 'Ildar HAFIZOV', 'by VSU', 'Feb 2016'),
('gr', '60 Kg', 'Erhan KARAKUS', 'Ildar HAFIZOV', ('', ''), 'Erhan KARAKUS', 'by PO', 'Sep 2009'),
('gr', '60 Kg', 'Sergey EMELIN', 'Kerem KAMAL', ('4', '1'), 'Sergey EMELIN', 'by VPO1', 'Apr 2021'),
('gr', '60 Kg', 'Kerem KAMAL', 'Hleb MAKARANKA', ('7', '2'), 'Kerem KAMAL', 'by VPO1', 'Apr 2021'),
('gr', '60 Kg', 'Kerem KAMAL', 'Viktor PETRYK', ('5', '1'), 'Kerem KAMAL', 'by VPO1', 'Apr 2021'),
('gr', '60 Kg', 'Kerem KAMAL', 'Etienne KINSINGER', ('5', '1'), 'Kerem KAMAL', 'by VPO1', 'Mar 2021'),
('gr', '60 Kg', 'Kerem KAMAL', 'Erik TORBA', ('5', '4'), 'Kerem KAMAL', 'by VPO1', 'Mar 2021'),
('gr', '60 Kg', 'Kerem KAMAL', 'Victor CIOBANU', ('9', '1'), 'Kerem KAMAL', 'by VSU1', 'Mar 2021'),
('gr', '60 Kg', 'Kerem KAMAL', 'Irakli DZIMISTARISHVILI', ('5', '1'), 'Kerem KAMAL', 'by VPO1', 'Mar 2021'),
('gr', '60 Kg', 'Gevorg GHARIBYAN', 'Kerem KAMAL', ('5', '5'), 'Gevorg GHARIBYAN', 'by VPO1', 'Feb 2020'),
('gr', '60 Kg', 'Kerem KAMAL', 'Amiran SHAVADZE', ('9', '0'), 'Kerem KAMAL', 'by VSU', 'Feb 2020'),
('gr', '60 Kg', 'Kerem KAMAL', 'Zhambolat LOKYAEV', ('6', '1'), 'Kerem KAMAL', 'by VPO1', 'Feb 2020'),
('gr', '60 Kg', 'Kerem KAMAL', 'Zhora ABOVIAN', ('6', '2'), 'Kerem KAMAL', 'by VPO1', 'Feb 2020'),
('gr', '60 Kg', 'Erbatu TUO', 'Kerem KAMAL', ('7', '1'), 'Erbatu TUO', 'by VPO1', 'Jan 2020'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Kerem KAMAL', ('4', '3'), 'Sailike WALIHAN', 'by VPO1', 'Jan 2020'),
('gr', '60 Kg', 'Kerem KAMAL', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('9', '0'), 'Kerem KAMAL', 'by VSU', 'Jan 2020'),
('gr', '60 Kg', 'Kerem KAMAL', 'Ahmet UYAR', ('3', '1'), 'Kerem KAMAL', 'by VPO1', 'Jan 2020'),
('gr', '60 Kg', 'Kanybek ZHOLCHUBEKOV', 'Kerem KAMAL', ('15', '7'), 'Kanybek ZHOLCHUBEKOV', 'by VSU1', 'Sep 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Sahak HOVHANNISYAN', ('7', '2'), 'Kerem KAMAL', 'by VPO1', 'Aug 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Talastan KANZHARBEK UULU', ('7', '4'), 'Kerem KAMAL', 'by VPO1', 'Aug 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Asgar ALIZADA', ('14', '6'), 'Kerem KAMAL', 'by VSU1', 'Aug 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Mourtada NAANAA', ('10', '1'), 'Kerem KAMAL', 'by VSU1', 'Aug 2019'),
('gr', '60 Kg', 'Victor CIOBANU', 'Kerem KAMAL', ('10', '9'), 'Victor CIOBANU', 'by VPO1', 'Jun 2019'),
('gr', '60 Kg', 'Stepan MARYANYAN', 'Kerem KAMAL', ('5', '2'), 'Stepan MARYANYAN', 'by VPO1', 'Jun 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Armen MELIKYAN', ('4', '0'), 'Kerem KAMAL', 'by VPO', 'Jun 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Virgil MUNTEANU', ('4', '1'), 'Kerem KAMAL', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Kerem KAMAL', ('7', '0'), 'Sergey EMELIN', 'by VPO', 'Apr 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Jacopo SANDRON', ('5', '0'), 'Kerem KAMAL', 'by VPO', 'Apr 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Ardit FAZLJIJA', ('3', '1'), 'Kerem KAMAL', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Dzmitry BRYCHAK', ('9', '0'), 'Kerem KAMAL', 'by VSU', 'Apr 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Razvan ARNAUT', ('6', '1'), 'Kerem KAMAL', 'by VPO1', 'Mar 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Irakli DZIMISTARISHVILI', ('9', '0'), 'Kerem KAMAL', 'by VSU', 'Mar 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Sadyk LALAEV', ('6', '5'), 'Kerem KAMAL', 'by VPO1', 'Mar 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Milad Ali REZANEZHAD', ('9', '3'), 'Kerem KAMAL', 'by VPO1', 'Feb 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Ivan LIZATOVIC', ('11', '1'), 'Kerem KAMAL', 'by VSU1', 'Feb 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Seunghak KIM', ('7', '2'), 'Kerem KAMAL', 'by VPO1', 'Feb 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Sandro FRANKOL', ('8', '0'), 'Kerem KAMAL', 'by VSU', 'Feb 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Islomjon BAKHRAMOV', ('9', '1'), 'Kerem KAMAL', 'by VSU1', 'Nov 2018'),
('gr', '60 Kg', 'Murad MAMMADOV', 'Kerem KAMAL', ('5', '2'), 'Murad MAMMADOV', 'by VPO1', 'Nov 2018'),
('gr', '60 Kg', 'Kerem KAMAL', 'Libin DING', ('10', '1'), 'Kerem KAMAL', 'by VSU1', 'Nov 2018'),
('gr', '60 Kg', 'Kerem KAMAL', 'Dastan ZARLYKHANOV', ('7', '6'), 'Kerem KAMAL', 'by VPO1', 'Nov 2018'),
('gr', '60 Kg', 'Kerem KAMAL', 'Ardit FAZLJIJA', ('4', '4'), 'Kerem KAMAL', 'by VPO1', 'Nov 2018'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Kerem KAMAL', ('7', '5'), 'Sailike WALIHAN', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Kerem KAMAL', 'Vijay VIJAY', ('10', '0'), 'Kerem KAMAL', 'by VSU', 'Sep 2018'),
('gr', '60 Kg', 'Kerem KAMAL', 'Razvan ARNAUT', ('8', '0'), 'Kerem KAMAL', 'by VSU', 'Sep 2018'),
('gr', '60 Kg', 'Kerem KAMAL', 'Ararat MANUCHARYAN', ('5', '3'), 'Kerem KAMAL', 'by VPO1', 'Sep 2018'),
('gr', '60 Kg', 'Kerem KAMAL', 'Kazuki YABE', ('8', '1'), 'Kerem KAMAL', 'by VPO1', 'Sep 2018'),
('gr', '60 Kg', 'Kerem KAMAL', 'Jacopo SANDRON', ('9', '0'), 'Kerem KAMAL', 'by VSU', 'Sep 2018'),
('gr', '60 Kg', 'Ararat MANUCHARYAN', 'Kerem KAMAL', ('9', '0'), 'Ararat MANUCHARYAN', 'by VSU', 'Jul 2018'),
('gr', '60 Kg', 'Kerem KAMAL', 'Artur Muchegovitch PETROSIAN', ('6', '3'), 'Kerem KAMAL', 'by VPO1', 'Jun 2018'),
('gr', '60 Kg', 'Kerem KAMAL', 'Teodor HORATAU', ('9', '1'), 'Kerem KAMAL', 'by VSU1', 'Jun 2018'),
('gr', '60 Kg', 'Kerem KAMAL', 'Murad MAMMADOV', ('5', '2'), 'Kerem KAMAL', 'by VPO1', 'Jun 2018'),
('gr', '60 Kg', 'Kerem KAMAL', 'Avgustin Boyanov SPASOV', ('7', '3'), 'Kerem KAMAL', 'by VPO1', 'Jun 2018'),
('gr', '60 Kg', 'Kerem KAMAL', 'Zholaman SHARSHENBEKOV', ('12', '3'), 'Kerem KAMAL', 'by VSU1', 'Aug 2017'),
('gr', '60 Kg', 'Kerem KAMAL', 'Turabek TIRKASHEV', ('10', '1'), 'Kerem KAMAL', 'by VSU1', 'Aug 2017'),
('gr', '60 Kg', 'Kerem KAMAL', 'Nugzari TSURTSUMIA', ('6', '6'), 'Kerem KAMAL', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Kerem KAMAL', 'Serghei JEPAN', ('9', '4'), 'Kerem KAMAL', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Kerem KAMAL', 'Emin Narimanovitch SEFERSHAEV', ('5', '3'), 'Kerem KAMAL', 'by VPO1', 'Jun 2017'),
('gr', '60 Kg', 'Kerem KAMAL', 'Mykhaylo STUPIN', ('8', '0'), 'Kerem KAMAL', 'by VSU', 'Jun 2017'),
('gr', '60 Kg', 'Kerem KAMAL', 'Dejan PETROVIC', ('8', '0'), 'Kerem KAMAL', 'by VSU', 'Jun 2017'),
('gr', '60 Kg', 'Kerem KAMAL', 'Helary MAEGISALU', ('7', '1'), 'Kerem KAMAL', 'by VPO1', 'Jun 2017'),
('gr', '60 Kg', 'Leri ABULADZE', 'Kerem KAMAL', ('3', '3'), 'Leri ABULADZE', 'by VPO1', 'Sep 2016'),
('gr', '60 Kg', 'Kerem KAMAL', 'Anar MANSUROV', ('5', '3'), 'Kerem KAMAL', 'by VPO1', 'Sep 2016'),
('gr', '60 Kg', 'Kerem KAMAL', 'Sachin RANA', ('8', '0'), 'Kerem KAMAL', 'by VSU', 'Sep 2016'),
('gr', '60 Kg', 'Kerem KAMAL', 'Aistis LIAUGMINAS', ('9', '0'), 'Kerem KAMAL', 'by VPO1', 'Sep 2016'),
('gr', '60 Kg', 'Kerem KAMAL', 'Dovudzhon TOSHEV', ('6', '1'), 'Kerem KAMAL', 'by VPO1', 'Jul 2016'),
('gr', '60 Kg', 'Shant KHACHATRYAN', 'Kerem KAMAL', ('9', '0'), 'Shant KHACHATRYAN', 'by VSU', 'Jul 2016'),
('gr', '60 Kg', 'Kerem KAMAL', 'Oleksandr TYESTOV', ('12', '7'), 'Kerem KAMAL', 'by VPO1', 'Jul 2016'),
('gr', '60 Kg', 'Kerem KAMAL', 'Yahor KHAKHLOU', ('10', '2'), 'Kerem KAMAL', 'by VSU1', 'Jul 2016'),
('gr', '60 Kg', 'Kerem KAMAL', 'Denis MERTL', ('6', '0'), 'Kerem KAMAL', 'by VFA', 'Jul 2016'),
('gr', '60 Kg', 'Turabek TIRKASHEV', 'Kerem KAMAL', ('5', '7'), 'Turabek TIRKASHEV', 'by VPO1', 'Aug 2015'),
('gr', '60 Kg', 'Kerem KAMAL', 'Simonyan SERGEY', ('10', '2'), 'Kerem KAMAL', 'by VSU1', 'Aug 2015'),
('gr', '60 Kg', 'Kerem KAMAL', 'Atmir KOTCEV', ('3', '2'), 'Kerem KAMAL', 'by VPO1', 'Aug 2015'),
('gr', '60 Kg', 'Kerem KAMAL', 'Marlen ASIKEEV', ('8', '0'), 'Kerem KAMAL', 'by VSU', 'Aug 2015'),
('gr', '60 Kg', 'Kerem KAMAL', 'Etienne KINSINGER', ('5', '1'), 'Kerem KAMAL', 'by VPO1', 'Mar 2021'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Murad MAMMADOV', ('5', '3'), 'Etienne KINSINGER', 'by VPO1', 'Mar 2021'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Ivan LIZATOVIC', ('8', '2'), 'Etienne KINSINGER', 'by VPO1', 'Mar 2021'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Helary MAEGISALU', ('5', '4'), 'Etienne KINSINGER', 'by VPO1', 'Mar 2021'),
('gr', '60 Kg', 'Ildar HAFIZOV', 'Etienne KINSINGER', ('6', '1'), 'Ildar HAFIZOV', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Jacopo SANDRON', 'Etienne KINSINGER', ('4', '0'), 'Jacopo SANDRON', 'by VPO', 'Apr 2019'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Erik TORBA', ('5', '4'), 'Etienne KINSINGER', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Etienne KINSINGER', ('4', '0'), 'Sailike WALIHAN', 'by VPO', 'Oct 2018'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Erik TORBA', ('5', '3'), 'Etienne KINSINGER', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Victor CIOBANU', 'Etienne KINSINGER', ('8', '1'), 'Victor CIOBANU', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Dalton James ROBERTS', ('11', '0'), 'Etienne KINSINGER', 'by VSU', 'Oct 2018'),
('gr', '60 Kg', 'Dato CHKHARTISHVILI', 'Etienne KINSINGER', ('1', '1'), 'Dato CHKHARTISHVILI', 'by VPO1', 'Apr 2018'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Erik TORBA', ('8', '0'), 'Etienne KINSINGER', 'by VSU', 'Apr 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Etienne KINSINGER', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Apr 2018'),
('gr', '60 Kg', 'Stepan MARYANYAN', 'Etienne KINSINGER', ('2', '2'), 'Stepan MARYANYAN', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Abdurrahman ALTAN', 'Etienne KINSINGER', ('2', '1'), 'Abdurrahman ALTAN', 'by VPO1', 'Mar 2017'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Przemyslaw PIATEK', ('3', '2'), 'Etienne KINSINGER', 'by VPO1', 'Mar 2017'),
('gr', '60 Kg', 'Kaly SULAIMANOV', 'Etienne KINSINGER', ('2', '1'), 'Kaly SULAIMANOV', 'by VPO1', 'Aug 2016'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Taylor Craig LA MONT', ('2', '1'), 'Etienne KINSINGER', 'by VPO1', 'Aug 2016'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Oleksandr HRUSHYN', ('3', '1'), 'Etienne KINSINGER', 'by VPO1', 'Aug 2016'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Stepan CRISTEA', ('5', '0'), 'Etienne KINSINGER', 'by VPO', 'Aug 2016'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Sagar SAGAR', ('5', '0'), 'Etienne KINSINGER', 'by VPO', 'Aug 2016'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Nestar Nedkov NESTAROV', ('8', '1'), 'Etienne KINSINGER', 'by VPO1', 'Jun 2016'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Alexandru SOLOMON', ('5', '2'), 'Etienne KINSINGER', 'by VPO1', 'Jun 2016'),
('gr', '60 Kg', 'Mikayil RAHMANOV', 'Etienne KINSINGER', ('1', '0'), 'Mikayil RAHMANOV', 'by VPO', 'Jun 2016'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Khvicha TCHITAVA', ('3', '3'), 'Etienne KINSINGER', 'by VPO1', 'Mar 2016'),
('gr', '60 Kg', 'Sergey EMELIN', 'Etienne KINSINGER', ('8', '0'), 'Sergey EMELIN', 'by VSU', 'Mar 2016'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Lauri Johannes MAEHOENEN', ('8', '0'), 'Etienne KINSINGER', 'by VSU', 'Mar 2016'),
('gr', '60 Kg', 'Etienne KINSINGER', 'Andriy MARTYNYUK', ('9', '0'), 'Etienne KINSINGER', 'by VSU', 'Mar 2016'),
('gr', '60 Kg', 'Khvicha TCHITAVA', 'Etienne KINSINGER', ('6', '2'), 'Khvicha TCHITAVA', 'by VPO1', 'Mar 2015'),
('gr', '60 Kg', 'Ekrem OZTURK', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('9', '0'), 'Ekrem OZTURK', 'by VSU', 'Jun 2021'),
('gr', '60 Kg', 'Mukhammadkodir YUSUPOV', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('4', '2'), 'Mukhammadkodir YUSUPOV', 'by VPO1', 'Jun 2021'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Abdelkarim FERGAT', ('10', '3'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Apr 2021'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Mehdi JOUINI', ('9', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Apr 2021'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Romio Ricardo GOLIATH', ('8', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Apr 2021'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Fouad FAJARI', ('3', '1'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Apr 2021'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Mehdi DHEKER', ('2', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO', 'Feb 2020'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Abderrazak ROUINBI', ('9', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Feb 2020'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Abdennour LAOUNI', ('2', '1'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Feb 2020'),
('gr', '60 Kg', 'Kerem KAMAL', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('9', '0'), 'Kerem KAMAL', 'by VSU', 'Jan 2020'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Giovanni FRENI', ('10', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Jan 2020'),
('gr', '60 Kg', 'Ali Reza Ayat Ollah NEJATI', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('3', '1'), 'Ali Reza Ayat Ollah NEJATI', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Dicther Hans TORO CASTANEDA', ('6', '4'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Fouad FAJARI', ('1', '1'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Aug 2019'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Jonathan Ngeta IBANDA', ('9', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Aug 2019'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Fouad FAJARI', ('3', '1'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Aug 2019'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Kenneth KOECH', ('4', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VFA', 'Aug 2019'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Radhwen TARHOUNI', ('8', '1'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VFA', 'Mar 2019'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Gert Cornelius Johannes COETZEE', ('9', '1'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU1', 'Mar 2019'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Abdeldjebar DJEBBARI', ('3', '2'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Mar 2019'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Fouad FAJARI', ('5', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO', 'Mar 2019'),
('gr', '60 Kg', 'Mustafa SAGLAM', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('7', '2'), 'Mustafa SAGLAM', 'by VPO1', 'Feb 2019'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Avgustin Boyanov SPASOV', ('8', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Feb 2019'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Victor CIOBANU', ('11', '2'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU1', 'Feb 2019'),
('gr', '60 Kg', 'Maksim KAZHARSKI', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('5', '1'), 'Maksim KAZHARSKI', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Sergey EMELIN', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', ('9', '0'), 'Sergey EMELIN', 'by VSU', 'Oct 2018'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Ivo Serafimov ANGELOV', ('7', '2'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Billel BENBRIH', ('7', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO', 'Apr 2016'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'El Mahadi MESSAOUDI', ('8', '0'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU', 'Apr 2016'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Sailike WALIHAN', ('4', '3'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Apr 2021'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Gyanender GYANENDER', ('6', '1'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Apr 2021'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Hanjae CHUNG', ('6', '2'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Apr 2021'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Stepan MARYANYAN', ('4', '4'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Dec 2020'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Ahmet UYAR', ('5', '1'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Dec 2020'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Victor CIOBANU', ('8', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Dec 2020'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Maksim KAZHARSKI', ('8', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Dec 2020'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Zholaman SHARSHENBEKOV', ('4', '0'), 'Kenichiro FUMITA', 'by VPO', 'Feb 2020'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Mehdi Seifollah MOHSEN NEJAD', ('9', '2'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Feb 2020'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Davaabandi MUNKH ERDENE', ('10', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Feb 2020'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Aidos SULTANGALI', ('7', '6'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Feb 2020'),
('gr', '60 Kg', 'Armen MELIKYAN', 'Zholaman SHARSHENBEKOV', ('11', '7'), 'Armen MELIKYAN', 'by VPO1', 'Oct 2019'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Zhora ABOVIAN', ('8', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Oct 2019'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Liguo CAO', ('9', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Oct 2019'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Artur Muchegovitch PETROSIAN', ('9', '9'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Oct 2019'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Asgar ALIZADA', ('4', '0'), 'Zholaman SHARSHENBEKOV', 'by VFA', 'Oct 2019'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Manish MANISH', ('4', '3'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Mar 2019'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Tumentsogt BOLD', ('8', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Mar 2019'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Mehdi Seifollah MOHSEN NEJAD', ('4', '0'), 'Zholaman SHARSHENBEKOV', 'by VPO', 'Mar 2019'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Dastan ZARLYKHANOV', ('10', '1'), 'Zholaman SHARSHENBEKOV', 'by VSU1', 'Mar 2019'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Zhambolat LOKYAEV', ('8', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Feb 2019'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Zholaman SHARSHENBEKOV', ('9', '4'), 'Sailike WALIHAN', 'by VPO1', 'Feb 2019'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Yernar FIDAKHMETOV', ('12', '2'), 'Zholaman SHARSHENBEKOV', 'by VSU1', 'Feb 2019'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Michal Jacek TRACZ', ('8', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Feb 2019'),
('gr', '60 Kg', 'Eldaniz AZIZLI', 'Zholaman SHARSHENBEKOV', ('10', '0'), 'Eldaniz AZIZLI', 'by VSU', 'Oct 2018'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Ekrem OZTURK', ('9', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Oct 2018'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Norayr HAKHOYAN', ('11', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Oct 2018'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Hee Dong SON', ('9', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Oct 2018'),
('gr', '60 Kg', 'Shota TANOKURA', 'Zholaman SHARSHENBEKOV', ('5', '4'), 'Shota TANOKURA', 'by VPO1', 'Feb 2018'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Liguo CAO', ('8', '2'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Feb 2018'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Khorlan ZHAKANSHA', ('14', '2'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Feb 2018'),
('gr', '60 Kg', 'Kerem KAMAL', 'Zholaman SHARSHENBEKOV', ('12', '3'), 'Kerem KAMAL', 'by VSU1', 'Aug 2017'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Tigran MINASYAN', ('12', '2'), 'Zholaman SHARSHENBEKOV', 'by VSU1', 'Aug 2017'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Emin Narimanovitch SEFERSHAEV', ('13', '1'), 'Zholaman SHARSHENBEKOV', 'by VSU1', 'Aug 2017'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Giovanni FRENI', ('8', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Aug 2017'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Krisztian KECSKEMETI', ('8', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Aug 2017'),
('gr', '60 Kg', 'Mohammad Javad Saadat REZAEI', 'Zholaman SHARSHENBEKOV', ('4', '4'), 'Mohammad Javad Saadat REZAEI', 'by VPO1', 'Jun 2017'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Yernur FIDAKHMETOV', ('9', '6'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Jun 2017'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Vijay VIJAY', ('2', '0'), 'Zholaman SHARSHENBEKOV', 'by VFA', 'Jun 2017'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Elnur MUSAYEV', ('3', '1'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Sep 2016'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Dilshod OMONGELDIYEV', ('10', '0'), 'Zholaman SHARSHENBEKOV', 'by VFA', 'Sep 2016'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Riccardo GLAVE', ('8', '0'), 'Zholaman SHARSHENBEKOV', 'by VFA', 'Sep 2016'),
('gr', '60 Kg', 'Leri ABULADZE', 'Zholaman SHARSHENBEKOV', ('8', '0'), 'Leri ABULADZE', 'by VSU', 'Sep 2016'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Real Marshall Ray WOODS', ('6', '0'), 'Zholaman SHARSHENBEKOV', 'by VPO', 'Sep 2016'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Kaniet KUBANOV', ('9', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Jul 2016'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Ju Chan KIM', ('9', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Jul 2016'),
('gr', '60 Kg', 'Adilet SISSEMBAYEV', 'Zholaman SHARSHENBEKOV', ('1', '1'), 'Adilet SISSEMBAYEV', 'by VPO1', 'Jul 2016'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Chun-Han TAI', ('10', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Jul 2016'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Sailike WALIHAN', ('4', '3'), 'Zholaman SHARSHENBEKOV', 'by VPO1', 'Apr 2021'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Firuz MIRZORAJABOV', ('10', '0'), 'Sailike WALIHAN', 'by VSU', 'Apr 2021'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Mohammad F Kh M J ALAJMI', ('9', '0'), 'Sailike WALIHAN', 'by VSU', 'Apr 2021'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Islomjon BAKHRAMOV', ('4', '3'), 'Sailike WALIHAN', 'by VPO1', 'Jan 2020'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Kerem KAMAL', ('4', '3'), 'Sailike WALIHAN', 'by VPO1', 'Jan 2020'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Erbatu TUO', ('13', '4'), 'Sailike WALIHAN', 'by VSU1', 'Jan 2020'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Ildar HAFIZOV', ('9', '1'), 'Sailike WALIHAN', 'by VSU1', 'Jan 2020'),
('gr', '60 Kg', 'Ivo Serafimov ANGELOV', 'Sailike WALIHAN', ('4', '0'), 'Ivo Serafimov ANGELOV', 'by VPO', 'Sep 2019'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Kanybek ZHOLCHUBEKOV', ('4', '3'), 'Sailike WALIHAN', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Stig Andre BERGE', ('3', '2'), 'Sailike WALIHAN', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Erbatu TUO', ('2', '1'), 'Sailike WALIHAN', 'by VPO1', 'Jul 2019'),
('gr', '60 Kg', 'Islomjon BAKHRAMOV', 'Sailike WALIHAN', ('3', '3'), 'Islomjon BAKHRAMOV', 'by VPO1', 'Jul 2019'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Aliaksandr PECHURENKA', ('9', '0'), 'Sailike WALIHAN', 'by VSU', 'Jul 2019'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Firuz TUKHTAEV', ('4', '0'), 'Sailike WALIHAN', 'by VPO', 'Jul 2019'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Sailike WALIHAN', ('0', '0'), 'Kenichiro FUMITA', 'by VIN', 'Apr 2019'),
('gr', '60 Kg', 'Se Ung RI', 'Sailike WALIHAN', ('5', '2'), 'Se Ung RI', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Jungbaik LEE', ('3', '1'), 'Sailike WALIHAN', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Rustam TEIISHOV', ('2', '0'), 'Sailike WALIHAN', 'by VPO', 'Apr 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Sailike WALIHAN', ('7', '2'), 'Sergey EMELIN', 'by VPO1', 'Feb 2019'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Zholaman SHARSHENBEKOV', ('9', '4'), 'Sailike WALIHAN', 'by VPO1', 'Feb 2019'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Dawid Andrzej ERSETIC', ('9', '0'), 'Sailike WALIHAN', 'by VSU', 'Feb 2019'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Zhambolat LOKYAEV', ('2', '1'), 'Sailike WALIHAN', 'by VPO1', 'Feb 2019'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Travis Michael RICE', ('9', '0'), 'Sailike WALIHAN', 'by VSU', 'Feb 2019'),
('gr', '60 Kg', 'Erbatu TUO', 'Sailike WALIHAN', ('7', '4'), 'Erbatu TUO', 'by VPO1', 'Feb 2019'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Kristian FRIS', ('9', '0'), 'Sailike WALIHAN', 'by VSU', 'Oct 2018'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Etienne KINSINGER', ('4', '0'), 'Sailike WALIHAN', 'by VPO', 'Oct 2018'),
('gr', '60 Kg', 'Victor CIOBANU', 'Sailike WALIHAN', ('6', '6'), 'Victor CIOBANU', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Przemyslaw PIATEK', ('4', '1'), 'Sailike WALIHAN', 'by VFA', 'Oct 2018'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Kerem KAMAL', ('7', '5'), 'Sailike WALIHAN', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Se Ung RI', 'Sailike WALIHAN', ('9', '0'), 'Se Ung RI', 'by VSU', 'Aug 2018'),
('gr', '60 Kg', 'Kanybek ZHOLCHUBEKOV', 'Sailike WALIHAN', ('6', '1'), 'Kanybek ZHOLCHUBEKOV', 'by VPO1', 'Aug 2018'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Gamal Mohammed Yahya ALSABRI', ('9', '0'), 'Sailike WALIHAN', 'by VSU', 'Aug 2018'),
('gr', '60 Kg', 'Kanybek ZHOLCHUBEKOV', 'Sailike WALIHAN', ('7', '1'), 'Kanybek ZHOLCHUBEKOV', 'by VPO1', 'Jun 2018'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Erbatu TUO', ('5', '5'), 'Sailike WALIHAN', 'by VPO1', 'Jun 2018'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Mohammad Eynollah FAGHIRI', ('5', '3'), 'Sailike WALIHAN', 'by VPO1', 'Jun 2018'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Dejan PETROVIC', ('8', '0'), 'Sailike WALIHAN', 'by VSU', 'Jun 2018'),
('gr', '60 Kg', 'Takayuki INOGUCHI', 'Sailike WALIHAN', ('6', '0'), 'Takayuki INOGUCHI', 'by VPO', 'Feb 2018'),
('gr', '60 Kg', 'Sailike WALIHAN', 'Ibrahim Yacoub Hammoudeh ARRAR', ('8', '0'), 'Sailike WALIHAN', 'by VSU', 'Feb 2018'),
('gr', '60 Kg', 'Victor CIOBANU', 'Armen MELIKYAN', ('0', '0'), 'Victor CIOBANU', 'by VIN', 'May 2021'),
('gr', '60 Kg', 'Victor CIOBANU', 'Dato CHKHARTISHVILI', ('2', '1'), 'Victor CIOBANU', 'by VFA', 'May 2021'),
('gr', '60 Kg', 'Victor CIOBANU', 'Firuz MIRZORAJABOV', ('14', '0'), 'Victor CIOBANU', 'by VCA', 'May 2021'),
('gr', '60 Kg', 'Victor CIOBANU', 'Helary MAEGISALU', ('8', '5'), 'Victor CIOBANU', 'by VPO1', 'May 2021'),
('gr', '60 Kg', 'Victor CIOBANU', 'Fouad FAJARI', ('0', '0'), 'Victor CIOBANU', 'by VFO', 'May 2021'),
('gr', '60 Kg', 'Irakli DZIMISTARISHVILI', 'Victor CIOBANU', ('9', '0'), 'Irakli DZIMISTARISHVILI', 'by VSU', 'Mar 2021'),
('gr', '60 Kg', 'Kerem KAMAL', 'Victor CIOBANU', ('9', '1'), 'Kerem KAMAL', 'by VSU1', 'Mar 2021'),
('gr', '60 Kg', 'Victor CIOBANU', 'Soslan DAUROV', ('7', '2'), 'Victor CIOBANU', 'by VPO1', 'Mar 2021'),
('gr', '60 Kg', 'Victor CIOBANU', 'Niklas OHLEN', ('8', '7'), 'Victor CIOBANU', 'by VPO1', 'Jan 2021'),
('gr', '60 Kg', 'Victor CIOBANU', 'Stig Andre BERGE', ('10', '0'), 'Victor CIOBANU', 'by VSU', 'Jan 2021'),
('gr', '60 Kg', 'Victor CIOBANU', 'Andrej GINC', ('7', '2'), 'Victor CIOBANU', 'by VPO1', 'Jan 2021'),
('gr', '60 Kg', 'Maksim KAZHARSKI', 'Victor CIOBANU', ('3', '1'), 'Maksim KAZHARSKI', 'by VPO1', 'Dec 2020'),
('gr', '60 Kg', 'Zholaman SHARSHENBEKOV', 'Victor CIOBANU', ('8', '0'), 'Zholaman SHARSHENBEKOV', 'by VSU', 'Dec 2020'),
('gr', '60 Kg', 'Victor CIOBANU', 'Nihat Zahid MAMMADLI', ('7', '0'), 'Victor CIOBANU', 'by VPO', 'Dec 2020'),
('gr', '60 Kg', 'Erik TORBA', 'Victor CIOBANU', ('10', '3'), 'Erik TORBA', 'by VPO1', 'Feb 2020'),
('gr', '60 Kg', 'Elmurat TASMURADOV', 'Victor CIOBANU', ('9', '0'), 'Elmurat TASMURADOV', 'by VSU', 'Sep 2019'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Victor CIOBANU', ('12', '5'), 'Kenichiro FUMITA', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Victor CIOBANU', 'Manish MANISH', ('10', '0'), 'Victor CIOBANU', 'by VSU', 'Sep 2019'),
('gr', '60 Kg', 'Victor CIOBANU', 'Helary MAEGISALU', ('6', '1'), 'Victor CIOBANU', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Victor CIOBANU', 'Zhora ABOVIAN', ('3', '1'), 'Victor CIOBANU', 'by VPO1', 'Jun 2019'),
('gr', '60 Kg', 'Victor CIOBANU', 'Kerem KAMAL', ('10', '9'), 'Victor CIOBANU', 'by VPO1', 'Jun 2019'),
('gr', '60 Kg', 'Stepan MARYANYAN', 'Victor CIOBANU', ('9', '1'), 'Stepan MARYANYAN', 'by VSU1', 'Jun 2019'),
('gr', '60 Kg', 'Victor CIOBANU', 'Sergey EMELIN', ('5', '5'), 'Victor CIOBANU', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Victor CIOBANU', 'Lenur TEMIROV', ('6', '4'), 'Victor CIOBANU', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Victor CIOBANU', 'Avgustin Boyanov SPASOV', ('10', '0'), 'Victor CIOBANU', 'by VSU', 'Apr 2019'),
('gr', '60 Kg', 'Victor CIOBANU', 'Ivan LIZATOVIC', ('3', '1'), 'Victor CIOBANU', 'by VPO1', 'Apr 2019'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Victor CIOBANU', ('11', '2'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VSU1', 'Feb 2019'),
('gr', '60 Kg', 'Sergey EMELIN', 'Victor CIOBANU', ('10', '1'), 'Sergey EMELIN', 'by VSU1', 'Oct 2018'),
('gr', '60 Kg', 'Victor CIOBANU', 'Kristian FRIS', ('6', '3'), 'Victor CIOBANU', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Victor CIOBANU', 'Sailike WALIHAN', ('6', '6'), 'Victor CIOBANU', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Victor CIOBANU', 'Etienne KINSINGER', ('8', '1'), 'Victor CIOBANU', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Victor CIOBANU', 'Erik TORBA', ('3', '3'), 'Victor CIOBANU', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Aidos SULTANGALI', 'Victor CIOBANU', ('0', '0'), 'Aidos SULTANGALI', 'by VIN', 'Jul 2018'),
('gr', '60 Kg', 'Victor CIOBANU', 'Sakit GULIYEV', ('10', '5'), 'Victor CIOBANU', 'by VPO1', 'Jul 2018'),
('gr', '60 Kg', 'Victor CIOBANU', 'Gyanender GYANENDER', ('7', '0'), 'Victor CIOBANU', 'by VPO', 'Jul 2018'),
('gr', '60 Kg', 'Armen MELIKYAN', 'Victor CIOBANU', ('8', '7'), 'Armen MELIKYAN', 'by VPO1', 'Apr 2018'),
('gr', '60 Kg', 'Taleh MAMMADOV', 'Victor CIOBANU', ('12', '9'), 'Taleh MAMMADOV', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Victor CIOBANU', 'Leo Alexandre Sylvain TUDEZCA', ('7', '5'), 'Victor CIOBANU', 'by VPO1', 'Aug 2017'),
('gr', '60 Kg', 'Revaz LASHKHI', 'Victor CIOBANU', ('6', '1'), 'Revaz LASHKHI', 'by VPO1', 'Apr 2016'),
('gr', '60 Kg', 'Stig-Andre BERGE', 'Victor CIOBANU', ('1', '1'), 'Stig-Andre BERGE', 'by VPO1', 'Apr 2016'),
('gr', '60 Kg', 'Victor CIOBANU', 'Erhan Turan KARAKUS', ('7', '3'), 'Victor CIOBANU', 'by VPO1', 'Apr 2016'),
('gr', '60 Kg', 'Roman AMOYAN', 'Victor CIOBANU', ('8', '2'), 'Roman AMOYAN', 'by VPO1', 'Sep 2015'),
('gr', '60 Kg', 'Victor CIOBANU', 'Zaur KABOLEV', ('5', '3'), 'Victor CIOBANU', 'by VPO1', 'Mar 2015'),
('gr', '60 Kg', 'Victor CIOBANU', 'Eldaniz AZIZLI', ('6', '2'), 'Victor CIOBANU', 'by VPO1', 'Mar 2015'),
('gr', '60 Kg', 'Victor CIOBANU', 'Vazgen KHACHATRYAN', ('3', '2'), 'Victor CIOBANU', 'by VPO1', 'Mar 2015'),
('gr', '60 Kg', 'Victor CIOBANU', 'Tamas NADJ', ('10', '0'), 'Victor CIOBANU', 'by VSU', 'Mar 2015'),
('gr', '60 Kg', 'Victor CIOBANU', 'Nikola VICHEV', ('7', '0'), 'Victor CIOBANU', 'by VFA', 'Mar 2015'),
('gr', '60 Kg', 'Deniz MENEKSE', 'Victor CIOBANU', ('6', '2'), 'Deniz MENEKSE', 'by VFA', 'Sep 2014'),
('gr', '60 Kg', 'Victor CIOBANU', 'Armen MELIKYAN', ('0', '0'), 'Victor CIOBANU', 'by VIN', 'May 2021'),
('gr', '60 Kg', 'Armen MELIKYAN', 'Hanjae CHUNG', ('5', '2'), 'Armen MELIKYAN', 'by VPO1', 'May 2021'),
('gr', '60 Kg', 'Armen MELIKYAN', 'Razvan ARNAUT', ('3', '1'), 'Armen MELIKYAN', 'by VPO1', 'May 2021'),
('gr', '60 Kg', 'Armen MELIKYAN', 'Justas PETRAVICIUS', ('9', '0'), 'Armen MELIKYAN', 'by VSU', 'May 2021'),
('gr', '60 Kg', 'Armen MELIKYAN', 'Samuel GURRIA VIGUERAS', ('10', '1'), 'Armen MELIKYAN', 'by VSU1', 'May 2021'),
('gr', '60 Kg', 'Gyanender GYANENDER', 'Armen MELIKYAN', ('3', '0'), 'Gyanender GYANENDER', 'by VPO', 'Dec 2020'),
('gr', '60 Kg', 'Armen MELIKYAN', 'Zholaman SHARSHENBEKOV', ('11', '7'), 'Armen MELIKYAN', 'by VPO1', 'Oct 2019'),
('gr', '60 Kg', 'Armen MELIKYAN', 'Krisztian KECSKEMETI', ('5', '0'), 'Armen MELIKYAN', 'by VPO', 'Oct 2019'),
('gr', '60 Kg', 'Armen MELIKYAN', 'Mehdi Seifollah MOHSEN NEJAD', ('4', '0'), 'Armen MELIKYAN', 'by VPO', 'Oct 2019'),
('gr', '60 Kg', 'Armen MELIKYAN', 'Martin Stoyanov VELEV', ('8', '0'), 'Armen MELIKYAN', 'by VSU', 'Oct 2019'),
('gr', '60 Kg', 'Kerem KAMAL', 'Armen MELIKYAN', ('4', '0'), 'Kerem KAMAL', 'by VPO', 'Jun 2019'),
('gr', '60 Kg', 'Zhora ABOVIAN', 'Armen MELIKYAN', ('7', '7'), 'Zhora ABOVIAN', 'by VPO1', 'Mar 2019'),
('gr', '60 Kg', 'Armen MELIKYAN', 'Mikkel LASSEN', ('8', '0'), 'Armen MELIKYAN', 'by VSU', 'Mar 2019'),
('gr', '60 Kg', 'Mehdi Seifollah MOHSEN NEJAD', 'Armen MELIKYAN', ('10', '1'), 'Mehdi Seifollah MOHSEN NEJAD', 'by VSU1', 'Nov 2018'),
('gr', '60 Kg', 'Armen MELIKYAN', 'Christopher Josef KRAEMER', ('9', '0'), 'Armen MELIKYAN', 'by VSU', 'Nov 2018'),
('gr', '60 Kg', 'Kenichiro FUMITA', 'Armen MELIKYAN', ('9', '6'), 'Kenichiro FUMITA', 'by VPO1', 'Nov 2018'),
('gr', '60 Kg', 'Armen MELIKYAN', 'Przemyslaw PIATEK', ('8', '0'), 'Armen MELIKYAN', 'by VSU', 'Nov 2018'),
('gr', '60 Kg', 'Mostafa Hassan Abdelaal MOHAMED', 'Armen MELIKYAN', ('3', '2'), 'Mostafa Hassan Abdelaal MOHAMED', 'by VPO1', 'Sep 2018'),    
('gr', '60 Kg', 'Erbatu TUO', 'Armen MELIKYAN', ('11', '9'), 'Erbatu TUO', 'by VPO1', 'Sep 2018'),
('gr', '60 Kg', 'Armen MELIKYAN', 'Di HU', ('9', '0'), 'Armen MELIKYAN', 'by VFA', 'Sep 2018'),
('gr', '60 Kg', 'Gevorg GHARIBYAN', 'Armen MELIKYAN', ('4', '3'), 'Gevorg GHARIBYAN', 'by VPO1', 'Jul 2018'),
('gr', '60 Kg', 'Dato CHKHARTISHVILI', 'Armen MELIKYAN', ('8', '4'), 'Dato CHKHARTISHVILI', 'by VPO1', 'Jun 2018'),
('gr', '60 Kg', 'Artur Muchegovitch PETROSIAN', 'Armen MELIKYAN', ('1', '1'), 'Artur Muchegovitch PETROSIAN', 'by VPO1', 'Jun 2018'),
('gr', '60 Kg', 'Dato CHKHARTISHVILI', 'Armen MELIKYAN', ('12', '4'), 'Dato CHKHARTISHVILI', 'by VSU1', 'Apr 2018'),
('gr', '60 Kg', 'Armen MELIKYAN', 'Victor CIOBANU', ('8', '7'), 'Armen MELIKYAN', 'by VPO1', 'Apr 2018'),
('gr', '60 Kg', 'Michal Jacek TRACZ', 'Abdelkarim FERGAT', ('6', '2'), 'Michal Jacek TRACZ', 'by VPO1', 'Jun 2021'),
('gr', '60 Kg', 'Olivier Tomasz SKRZYPCZAK', 'Abdelkarim FERGAT', ('6', '3'), 'Olivier Tomasz SKRZYPCZAK', 'by VFA', 'Jun 2021'),
('gr', '60 Kg', 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'Abdelkarim FERGAT', ('10', '3'), 'Haythem Mahmoud Ahmed Fahmy MAHMOUD', 'by VPO1', 'Apr 2021'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Fouad FAJARI', ('5', '3'), 'Abdelkarim FERGAT', 'by VPO1', 'Apr 2021'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Josh FAILAUGA', ('8', '0'), 'Abdelkarim FERGAT', 'by VSU', 'Apr 2021'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Mehdi JOUINI', ('10', '0'), 'Abdelkarim FERGAT', 'by VSU', 'Apr 2021'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Artiom DELEANU', ('6', '4'), 'Abdelkarim FERGAT', 'by VPO1', 'Dec 2020'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Cristian Vasile VAGIUNIC', ('14', '5'), 'Abdelkarim FERGAT', 'by VSU1', 'Dec 2020'),
('gr', '60 Kg', 'Serif KILIC', 'Abdelkarim FERGAT', ('10', '0'), 'Serif KILIC', 'by VSU', 'Dec 2020'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Dhia Eddine BAALOUCHI', ('11', '2'), 'Abdelkarim FERGAT', 'by VSU1', 'Feb 2020'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Youssef Mohamed Harbi THABET', ('16', '6'), 'Abdelkarim FERGAT', 'by VSU', 'Feb 2020'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Ismail ETTALIBI', ('6', '0'), 'Abdelkarim FERGAT', 'by VFA', 'Feb 2020'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Romio Ricardo GOLIATH', ('4', '3'), 'Abdelkarim FERGAT', 'by VPO1', 'Feb 2020'),
('gr', '60 Kg', 'Max Emiliano NOWRY', 'Abdelkarim FERGAT', ('11', '3'), 'Max Emiliano NOWRY', 'by VSU1', 'Sep 2019'),
('gr', '60 Kg', 'Khorlan ZHAKANSHA', 'Abdelkarim FERGAT', ('9', '5'), 'Khorlan ZHAKANSHA', 'by VPO1', 'Sep 2019'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Romio Ricardo GOLIATH', ('8', '0'), 'Abdelkarim FERGAT', 'by VSU', 'Mar 2019'),
('gr', '60 Kg', 'Ahmed Fouad Fouad Hussein BAGHDOUDA', 'Abdelkarim FERGAT', ('6', '4'), 'Ahmed Fouad Fouad Hussein BAGHDOUDA', 'by VPO1', 'Mar 2019'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Salim HAMDI', ('0', '0'), 'Abdelkarim FERGAT', 'by VFO', 'Mar 2019'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Jozsef ANDRASI', ('9', '0'), 'Abdelkarim FERGAT', 'by VSU', 'Feb 2019'),
('gr', '60 Kg', 'Javokhir MIRAKHMEDOV', 'Abdelkarim FERGAT', ('11', '6'), 'Javokhir MIRAKHMEDOV', 'by VPO1', 'Feb 2019'),
('gr', '60 Kg', 'Ilkhom BAKHROMOV', 'Abdelkarim FERGAT', ('6', '4'), 'Ilkhom BAKHROMOV', 'by VPO1', 'Feb 2019'),
('gr', '60 Kg', 'Reza Kheirollah KHEDRI', 'Abdelkarim FERGAT', ('8', '0'), 'Reza Kheirollah KHEDRI', 'by VSU', 'Feb 2019'),
('gr', '60 Kg', 'Sargis KHACHATRYAN', 'Abdelkarim FERGAT', ('5', '3'), 'Sargis KHACHATRYAN', 'by VPO1', 'Oct 2018'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Tamas TOEROEK', ('14', '7'), 'Abdelkarim FERGAT', 'by VPO1', 'Jun 2018'),
('gr', '60 Kg', 'Zhanserik SARSENBIYEV', 'Abdelkarim FERGAT', ('11', '2'), 'Zhanserik SARSENBIYEV', 'by VSU1', 'Jun 2018'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Marat GARIPOV', ('9', '5'), 'Abdelkarim FERGAT', 'by VPO1', 'Jun 2018'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Mahmoud Hussein Hemdan HUSSEIN', ('5', '1'), 'Abdelkarim FERGAT', 'by VPO1', 'Feb 2018'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Henry James AKINWALE', ('6', '0'), 'Abdelkarim FERGAT', 'by VFA', 'Feb 2018'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Given SIKHOSANA', ('10', '0'), 'Abdelkarim FERGAT', 'by VFA', 'Feb 2018'),
('gr', '60 Kg', 'Abdelkarim FERGAT', 'Abderrazak ROUINBI', ('0', '0'), 'Abdelkarim FERGAT', 'by DSQ', 'Feb 2018')]
    return arr